### ISSUE TITLE
New doc site go-live infrastructure change over

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#1]
We've set the go-live date for the new documentation site for June 3rd. These are the infrastructure changes I believe need to happen as part of the change over: 

- [x] transition the [github.io](https://github.com/medic/medic.github.io) to the new cht-docs repo (currently "beta" repo, will be renamed to cht-docs)
- [x] replace [current doc site](https://docs.communityhealthtoolkit.org/) with the new doc site: https://docs.communityhealthtoolkit.org/beta/docs/
- [x] automate PR process for documentation resource updates

cc: @abbyad feel free to add/clarify

**Comment by abbyad** [comment]
Closing as this is officially complete.
