### ISSUE TITLE
Improve '.transitions'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#1006]
Page: /apps/reference/app-settings/transitions/
Version: 2023-03-07 16:54:22 -0600 -0600
---

The use of the Latin acronym `NB` [should be avoided](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#latin-phrases), especially twice on the same line.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/789512/229617991-681a1d39-64cc-4f32-80e8-b689522668e3.png">

**Comment by esthermmoturi** [comment]
Fixed by https://github.com/medic/cht-docs/pull/1007
