### ISSUE TITLE
Improvements bulk upload docs based on user feedback

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1016]
* add which fields are required to [bulk upload templates](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/) on docs
* In [users-bulk-load docs about the spreadsheet](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/#spreadsheet) it says "Copy in error messages here after importing" but they don't know what errors we're talking about b/c they're reading it for the first time
* [user create API docs says](https://docs.communityhealthtoolkit.org/apps/reference/api/#post-apiv1users) "token login is required" and we should tell devs it's ok to have on local instance and they can check outbound messages to get token login links - and it will work w/o message gateway
* See if we can code vlookup to be LAST CELL instead hard coded to some random number that is too low eg 900 which will be too low after more rows of places/UUIDs are added

**Comment by esthermmoturi** [comment]
@mrjones-plip We can also include the following changes:

- Move the page info bit to the top of the page
- Move the 'Notes for how to bulk load users' to below the page info bit and rename it to 'Steps to bulk load users' or something similar
- Is there high level documentation on what this component does? If there is none maybe we can consider adding a short paragraph here. The information seems like it deep dives immediately.
