### ISSUE TITLE
Broken image on 'Grafana and Prometheus Setup'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#1033]
Page: /apps/guides/hosting/monitoring/setup/
Version: 2023-04-19 14:59:26 -0700 -0700
---

The screenshot is not displaying as intended. Fortunately it has a nice alt text!

<img width="464" alt="image" src="https://user-images.githubusercontent.com/789512/233503060-86bfe955-3c9c-4e2a-9f63-07a61659477b.png">

**Comment by mrjones-plip** [comment]
some how the testing @abbyad  and I did earlier today re-broke this.  opening up for a new PR to fix again...somehow...
