### ISSUE TITLE
Update Archicture Diagram: Add Watchdog, split into 3 diagrams

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1061]
On the [architecture page](https://docs.communityhealthtoolkit.org/core/overview/architecture/), we should add [CHT Watchdog](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/setup/). to the diagram.  However, @garethbowen  suggests now that this diagram is getting complex, we should split it up into 3:
* CHT Core
* CHT Sync
* CHT Watchdog

We should also consider using Mermaid for this now that it's enabled.  Otherwise, the original diagram is [here in Google Slides](https://docs.google.com/presentation/d/1j4jPsi-gHbiaLBfgYOyru1g_YV98PkBrx2zs7bwhoEQ/edit#slide=id.p).

**Comment by andrablaj** [comment]
Thanks @mrjones-plip for moving this forward so quickly! Should we add CHT interoperability per @garethbowen's suggestion?

**Comment by mrjones-plip** [comment]
oh, sure!  let's do 'em all while we're in there!

**Comment by andrablaj** [comment]
FYI @Phil-Mwago, to have your eyes also on this.

**Comment by mrjones-plip** [comment]
FYI - wanting to close this out, so only doing the three cited in the body above, cc -@andrablaj and @Phil-Mwago .  

Feel free to open another PR and use our existing diagrams in [Google Slides](https://docs.google.com/presentation/d/1j4jPsi-gHbiaLBfgYOyru1g_YV98PkBrx2zs7bwhoEQ/edit#slide=id.p)!
