### ISSUE TITLE
Add info about when/how often syncing is attempted

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-docs#1095]
Would be useful to document when syncing is attempted.

Here are some relevant resources that could be rolled up and documented in the "[Sync Status](https://docs.communityhealthtoolkit.org/apps/concepts/navigation/#sync-status)" section (or elsewhere). 

- [Forum Post with all (well, most of) the details](https://forum.communityhealthtoolkit.org/t/for-offline-users-how-often-does-the-app-try-to-refresh-if-there-is-an-available-internet-connection/503/2?u=michael )
- https://github.com/medic/cht-core/issues/5738#issuecomment-621934539
- https://github.com/medic/cht-core/issues/6299

**Comment by latin-panda** [comment]
@michaelkohn, I guess what you need is telemetry, right? Is the number of times people sync okay?

**Comment by michaelkohn** [comment]
@latin-panda this is just about **_documenting_** the current sync strategy on the docs site :-) ... I believe the forum post contains most of the details (though I'm not sure if things have changed at all since 2019), I just want that to be on the docs site somewhere.

**Comment by latin-panda** [comment]
Oh okay, easy then. Thanks @michaelkohn

**Comment by latin-panda** [comment]
Ideas to document:
- Internal process
- Different types of sync (manual, automated)
- Type of documents / data
Not sure if to also cover when it prompts to reload the app? (when config changes, when there's a new version of the app (src), when there's a new form, etc)

**Comment by michaelkohn** [comment]
Yep.... some important details we'd want to cover:

1. That offline users have (I think) two databases that get synced (the main one and the meta DB)
2. The types of docs you'll find in each of those DBs (telemetry, feedback, etc... in meta | reports, contacts, etc... in the main DB)
3. When do each of these databases normally get synced (automatically while there's a connection, whenever there is a change, when the app notices it comes back online, etc...)  
4. Any differences in how things are handled if there are server changes vs. client changes 
5. What other things will trigger a sync (logging in, reloading the app, etc....)

> Not sure if to also cover when it prompts to reload the app?

Jenni did some good investigation in [this slack thread
](https://medic.slack.com/archives/C02GME3BQE6/p1648194230211909?thread_ts=1648024569.425659&cid=C02GME3BQE6). I'd love for us to document this as well, but am OK doing it as a separate issue.

**Comment by Benmuiruri** [comment]
Closed by #1235

**Comment by michaelkohn** [comment]
Quick link to where this got updated on the docs site

https://docs.communityhealthtoolkit.org/apps/concepts/navigation/#sync-status
