### ISSUE TITLE
local-ip.medicmobile.org doesn't resolve on GH runners, causes link check errors

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1106]
When the [link checker script](https://github.com/medic/cht-docs/blob/main/.github/scripts/muffet.sh) runs, it fails to resolve [local-ip URLs](https://local-ip.medicmobile.org), which gives an error.

```
2m 51s
Run ./.github/scripts/muffet.sh
  ./.github/scripts/muffet.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.18.10/x64
http://localhost:1313/apps/tutorials/local-setup/
	lookup local-ip.medicmobile.org: Temporary failure in name resolution	https://local-ip.medicmobile.org/
http://localhost:1313/apps/guides/hosting/3.x/offline/
	lookup local-ip.medicmobile.org: Temporary failure in name resolution	https://local-ip.medicmobile.org/
Error: Process completed with exit code 1.
```

**Comment by mrjones-plip** [comment]
so far unable to reproduce:

*    found the [docker image GH uses](https://github.com/catthehacker/docker_images/pkgs/container/ubuntu) (or close enough hopefully): `docker run -d --name muffet ghcr.io/catthehacker/ubuntu:act-22.04 tail -f /dev/null`
*    spun up a local container, installed go 1.18 and muffet 1.5.7 (`docker exec -it muffet bash` and then some curl love with `https://golang.org/dl/go1.16.7.linux-amd64.tar.gz`  and then muffet with `GO111MODULE=on go install github.com/raviqqe/muffet@v1.5.7`)
*    ran [the script](https://github.com/medic/cht-docs/blob/main/.github/scripts/muffet.sh) against a local webserver with a local-ip link

I suspect this is endemic to GH runner DNS - so must reproduce in situ....my last favorite situ-ation to be in :(

**Comment by mrjones-plip** [comment]
Given the recent issues with DNS on local-ip (see [here](https://github.com/medic/cht-core/issues/8289) and [here](https://github.com/medic/cht-core/issues/8100)), I'm doing a bit of a deep dive to see if this is endemic to GH CI or [localtls](https://github.com/Corollarium/localtls) instance on https://local-ip.medicmobile.org

**Comment by mrjones-plip** [comment]
Using [this repo](https://github.com/mrjones-plip/muffet-ci-dns-test), I've reproduced the problem with a simple `dig` call:

```

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> local-ip.medicmobile.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 15992
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;local-ip.medicmobile.org.	IN	A

;; Query time: 580 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Jun 08 17:45:34 UTC 2023
;; MSG SIZE  rcvd: 53
```

**Comment by mrjones-plip** [comment]
Getting a bit further, I've uncovered the DNS server used in GH CI (`168.63.129.16`) and reproduced the problem using the specific server in a runner, but it succeeds when testing outside a runner on my local host?!

```
------------------------
calling: resolvectl status eth0
Link 2 (eth0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 168.63.129.16
       DNS Servers: 168.63.129.16
        DNS Domain: xaapicw3gjmereppnaj1kw40ib.bx.internal.cloudapp.net

------------------------
running: dig local-ip.medicmobile.org +short

------------------------
running: dig local-ip.medicmobile.org +short @9.9.9.9
15.188.129.97

------------------------
running: dig local-ip.medicmobile.org  +short @8.8.8.8
15.188.129.97

------------------------
running: dig local-ip.medicmobile.org  +short @168.63.129.16
```

**Comment by andrablaj** [comment]
Reopening this issue as the problem [seems to persist](https://github.com/medic/cht-docs/commit/bec510a0b936fbbee6bddbfb82457f7067d97ae5/checks).

**Comment by andrablaj** [comment]
It looks like this doesn't happen anymore. Closing the issue.
