### ISSUE TITLE
Improve 'API to interact with CHT Applications': Empty place holders

### ISSUE THREAD

**Issue by yrimal** [medic/cht-docs#1108]
Page: /apps/reference/api/
Version: 2023-05-12 08:26:27  0700  0700
---

<img width="623" alt="image" src="https://github.com/medic/cht-docs/assets/6102813/c3a64248-761a-4d1c-83c0-dff23af2ae08">

There are empty placeholders, refer to above image.

**Comment by garethbowen** [comment]
Fixed, and while I was there, removed the deep nesting so the toc is a little easier to use.
