### ISSUE TITLE
Update local setup guide

### ISSUE THREAD

**Issue by jkuester** [medic/cht-docs#1129]
https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/ 

- Update macOS steps for Python install to point to Python3
- Update Docker Linux steps to use Docker Desktop for Linux (verify that works first...)

**Comment by esthermmoturi** [comment]
Hey @jkuester , are you still up to updating this?

**Comment by jkuester** [comment]
@esthermmoturi I can give this a shot.  Do you happen to have macOS?  I just need to confirm with someone about the commands for installing python....

**Comment by esthermmoturi** [comment]
Hey @jkuester , I do have macOS.
