### ISSUE TITLE
CHT docsite google search indexing mishaps

### ISSUE THREAD

**Issue by esthermmoturi** [medic/cht-docs#1135]
Investigate and document mishaps when searching for certain items on the doc-site as discussed in [this](https://medic.slack.com/archives/C0437LKSKM4/p1682992427148249) slack conversation.

**Comment by garethbowen** [comment]
I'm working through a potential fix, but it's very slow (I have to manually request indexing and there is a quote of 10 requests per day). I'll post an update when finished and verified.

**Comment by garethbowen** [comment]
The process is...

1. Go to search.google.com
2. Find all "discovered - not indexed"
3. Select each
4. Click "request indexing"

Do 10 every 24 hours until all are resolved.

**Comment by garethbowen** [comment]
I think this is resolved. We'll need to keep an eye on it to make sure it doesn't come back, but hopefully it was just a bunch of pages that were stuck and now they're unstuck...
