### ISSUE TITLE
fix 2 broken links in docs

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1161]
per CI:

>  http://localhost:1313/apps/guides/integrations/rapidpro/
>	timeout	https://youtu.be/WcFhpSFhFug
> http://localhost:1313/apps/concepts/interoperability/
>	timeout	https://wiki.ohie.org/display/CP/Use+Case+Summary%3A+Request+Community+Based+Follow-Up
> Error: Process completed with exit code 1.

**Comment by andrablaj** [comment]
Closing this issue as those links seem to work fine now.
