### ISSUE TITLE
Improve 'Core Framework Releases'

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-docs#1203]
Page: /core/releases/
Version: 2023-10-10 19:56:20  1300  1300
---

<img width="923" alt="image" src="https://github.com/medic/cht-docs/assets/6102813/d30a06a7-f608-43fc-9915-b3dad376acdd">

Latest version of 4.x now run on couchdb 3.3.2, update document to correct this.

**Comment by 1yuv** [comment]
I am planning to a) make new entry for 4.4.x+ in dependencies table here @garethbowen . Another option b) is to just add, 3.3.2 onwards 4.4.x on the CouchdBD column. 

![image](https://github.com/medic/cht-docs/assets/6102813/964c11fd-b508-408e-a405-f747c5c292ac)

![image](https://github.com/medic/cht-docs/assets/6102813/7bc9e220-9c17-4c5b-9878-7a61668275a5)

Which one would be more appropriate a, or b ? Also, I saw NodeJS version is empty for 4.x. I can update that as a part of this issue. If we decide to go with option a, do we need to update version for any other softwares?

**Comment by garethbowen** [comment]
The reason NodeJS is empty is because it's fully contained inside the Docker container now - the installer doesn't have to know about it, so please leave that N/A.

I think go for your option a). Both options are kind of ugly but that's our fault for bumping a dependency outside a major.

Thanks!

**Comment by 1yuv** [comment]
Thanks @garethbowen . How can I find in CHT-Core if browser version support or supported version for other tools changed in between? Do you have any notable updates that you'd like to mention for browser or cht-android?

**Comment by garethbowen** [comment]
We're not allowed to change them except in major releases. The CouchDB change was a mistake as it should have happened in 4.0.
