### ISSUE TITLE
Documentation on PHC use cases supported by the CHT

### ISSUE THREAD

**Issue by helizabetholsen** [medic/cht-docs#123]
Do we want to include a list or other short description of the different PHC use cases supported by the CHT?

We reference many of these use cases in our Impact Metrics guide but I don't actually see a list or short descriptions of PHC activities supported by the CHT in our documentation (I could be missing it). It would be valuable to show these, perhaps in the examples section or elsewhere?

@MaxDiz what do you think?

**Comment by MaxDiz** [comment]
As discussed with @helizabetholsen , we are replacing this issue with #156 #157 #158 #159 #160 so they can be prioritized individually
