### ISSUE TITLE
Document how to connect a Superset instance to cht-sync data

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-docs#1298]
Given that we will not be shipping cht-sync with a superset Docker container we need to document how users can connect a superset instance to postgres to read cht-sync data and create dashboards. The documentation should cover both development and production instances.

This documentation can later be extended to include how to import a sample dashboard if we do provide that in the near future.

**Comment by andrablaj** [comment]
We link in [the docs site](https://docs.communityhealthtoolkit.org/apps/guides/data/analytics/setup/#setup-superset) the Superset documentation for how to connect to a PostgreSQL database, so this ticket is not needed anymore.
