### ISSUE TITLE
registo de gravidas nas estruturas de saude Guine Bissau

### ISSUE THREAD

**Issue by saude2024** [medic/cht-docs#1379]
Page: /apps/reference/forms/app/
Version: 2024-04-15 14:37:43  0800  0800
---

**Comment by andrablaj** [comment]
Hi @saude2024! Can you please add more details to this issue you opened about the functionality or issue you are encountering?

**Comment by saude2024** [comment]
Yes, it is working.

A quarta, 8/05/2024, 15:45, Andra Blaj ***@***.***> escreveu:

**Comment by andrablaj** [comment]
Good to hear! I will close the issue for now, as it doesn't seem to need any updates on the cht-core.
