### ISSUE TITLE
Improve robots.txt and sitemap.xml to improve search engine crawling

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-docs#138]
The site has a [robots.txt](https://docs.communityhealthtoolkit.org/robots.txt) but I think it needs a couple of tweaks, firstly to include `Disallow:`, and secondly to reference the sitemap.xml, eg:

```
User-agent: *
Disallow:

Sitemap: /sitemap.xml
```

We also have a [sitemap.xml](https://docs.communityhealthtoolkit.org/sitemap.xml) but I'm not sure it's up to date, for one thing it doesn't list the home page as one of the pages.

**Comment by abbyad** [comment]
I see this entry in the sitemap.xml:
```xml
<loc>https://docs.communityhealthtoolkit.org/</loc>
<lastmod>2020-06-04T16:05:57-04:00</lastmod>
```

Were you expecting another home page entry?

On a related note, I am moving away from offline search to Google Search for the site, which should help with some of this as well.

**Comment by garethbowen** [comment]
> I see this entry in the sitemap.xml:

So it is! Sorry about that... I must've skimmed right past it.

> Were you expecting another home page entry?

No that's perfect.

**Comment by abbyad** [comment]
It's automated by Hugo, so I wasn't taking it personally :)

**Comment by abbyad** [comment]
Search is now included. Will need to go through a small process to remove Google ads.

**Comment by garethbowen** [comment]
Looks great. There's a tab for "discussion" which shows search results from the forum. Should that be renamed to "Forum" so it's clearer what it is?

**Comment by abbyad** [comment]
The site is searchable, and ads have been removed. Some deeper pages have yet to be crawled and indexed so won't be included in the search just yet. If searching in Google with the full path of a page doesn't yield the page itself as a result, then the page has yet to be indexed.

Re Forum vs Discussion: Waiting on input from @CescaGarrett on that, and it is easily updated.

**Comment by abbyad** [comment]
Heard via DM from Francesca, and she thinks _Discussion_ is more appropriate in this context.

Also, searches of deeper pages seem to be found:
![image](https://user-images.githubusercontent.com/789512/84721816-882ab980-af4f-11ea-8900-288dcbf5c273.png)

@garethbowen, with that is this issue ready to be closed?

**Comment by garethbowen** [comment]
Sure!
