### ISSUE TITLE
Improve 'Getting started building a CHT app'

### ISSUE THREAD

**Issue by SangharshaPyakurel** [medic/cht-docs#1389]
Page: /
Version: 2024-04-17 08:14:28  0100  0100
---
Please make clear on the docs that what issue come after tasks.js because there is hide of default contact form and adding anything so please update the docs with saying what comes after tasks.js update and how to again create contact forms to i got the issue on and i solve this problem by the help of Binod Adhikary Sir in forum but i want to make documentation must clearly what the results come too for new developer .

**Comment by binokaryg** [comment]
Thanks @SangharshaPyakurel for creating the issue.

Adding some context:
CHT docs page: https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/
Forum post: https://forum.communityhealthtoolkit.org/t/uploading-tasks-js-break-everything/3499/21

**Comment by esthermmoturi** [comment]
Hey @binokaryg , I have reviewed the mentioned gap in the documentation. I don't see any direct mention of tasks.js. Once the cht-core has been cloned, everything should work as expected. Am I missing somthing?

**Comment by binokaryg** [comment]
I am not fully sure what @SangharshaPyakurel was suggesting, but I guess the contact formss got deleted somehow.

One improvement to make sure that the config matches with the default one could be adding the deployment command between these two steps in the section [upload-test-data](https://docs.communityhealthtoolkit.org/building/local-setup/#upload-test-data).

From:
```
git clone https://github.com/medic/cht-core.git
...
cht --url=https://medic:password@localhost --accept-self-signed-certs csv-to-docs upload-docs
```

To:
```
git clone https://github.com/medic/cht-core.git
...
cht --url=https://medic:password@localhost //<------------------------------------------------------ this line
cht --url=https://medic:password@localhost --accept-self-signed-certs csv-to-docs upload-docs
```

**Comment by esthermmoturi** [comment]
So we should replace this line  `cht --url=https://medic:password@localhost --accept-self-signed-certs csv-to-docs upload-docs`
with this line  `cht --url=https://medic:password@localhost --accept-self-signed-certs`
