### ISSUE TITLE
Improve 'Building CHT Android Flavors'

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-docs#1399]
Page: /apps/guides/android/branding/
Version: 2024-05-09 16:20:33  0200  0200
---

https://docs.communityhealthtoolkit.org/apps/guides/android/branding#5-release-the-new-flavor
> 5.4 [Release the flavor](https://docs.communityhealthtoolkit.org/apps/guides/android/publishing/)

The link `Release the flavor` should probably take us to the [releasing instructions](https://docs.communityhealthtoolkit.org/contribute/code/android/releasing/), not the publishing one. There's a separate section just below in step 6 which has a link to the publishing instructions.

> 6. Publish the app
The last step is to publish it in the Play Store, or whatever option best suit your needs. Checkout the [Publishing](https://docs.communityhealthtoolkit.org/apps/guides/android/publishing/) page to see all the options available and instructions.

**Comment by garethbowen** [comment]
@sugat009 You just worked on improvements to these pages - what do you think?

**Comment by sugat009** [comment]
I agree with @binokaryg 's sentiments and this could have been a bug when adding the link.

**Comment by sugat009** [comment]
PR has been created to address this.
On a side note, in this repo, both `master` and `main` branches seem to exist. (Spend some time debugging why the content in question does not exist/seems different when I accidentally switched to master instead of main). I assume that the `master` branch can be deleted? @garethbowen

**Comment by garethbowen** [comment]
@sugat009 Yes I agree - it's 500+ commits behind and 0 commits ahead, so it doesn't have anything of value and is confusing. Please delete it.
