### ISSUE TITLE
Update CHT Sync architecture elements

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-docs#1405]
Following the [architecture changes](https://docs.google.com/document/d/1qqXQ-O9Fimn6UvVQUf5BsOF96caoK1xo0uYZbXzYdSs/edit) in CHT Sync, update the existing documentation to match the new system design approach.

**Comment by mrjones-plip** [comment]
couple of notes for whoever does the work - I think the [CHT Sync and CHT Pipeline](https://docs.communityhealthtoolkit.org/core/overview/cht-sync/) page is the one being referenced in this ticket.  There's a [google drawing](https://docs.google.com/presentation/d/1j4jPsi-gHbiaLBfgYOyru1g_YV98PkBrx2zs7bwhoEQ/) that has the original diagram for this page.  Keep [the comment](https://github.com/medic/cht-docs/blob/bc31562fb8f060ac288592f728b4f0b1b94043c9/content/en/core/overview/cht-sync.md?plain=1#L21) on that page there for future archeologists!
