### ISSUE TITLE
House hold mapped and registered

### ISSUE THREAD

**Issue by vinsunda** [medic/cht-docs#1407]
I appreciate the kind work you have done in developing this community health toolkits however I would recommend as a user of the same if we would get numbers of household registered per month in the echis by the CHP or the CHA can be able to see the total numbers without counting manually while scrolling down the app.

Kind Regards
Vincent Sunda

**Comment by garethbowen** [comment]
Welcome @vinsunda 

It should be possible to configure the app to show this information in a target: https://docs.communityhealthtoolkit.org/apps/features/targets/

Please reach out to your supervisor or IT administrator to add this.

For further support I recommend posting to the [CHT forum](https://forum.communityhealthtoolkit.org/) where the community can support to set this up.

**Comment by mrjones-plip** [comment]
Seconding @garethbowen 's comment that the feedback is very welcome, but that this is the docs repository where we update https://docs.communityhealthtoolkit.org/.  As such, I'm closing this ticket as it's not actionable to update any docs content.

**Comment by vinsunda** [comment]
Well  noted, thank you.
