### ISSUE TITLE
Update CHT training resources

### ISSUE THREAD

**Issue by antonykhaemba** [medic/cht-docs#1430]
Updating the end user training resources based on the [feedback](https://docs.google.com/document/d/1jou1OaRTov341L8LUjv0iffW5LbRrb9eiXX0l-0GkiE/edit?usp=sharing) shared by users.

**Comment by esthermmoturi** [comment]
@antonykhaemba , is it possible to finish this and have it up on the docs site by EoW- next week?

**Comment by esthermmoturi** [comment]
Solved by https://github.com/medic/cht-docs/pull/1431
