### ISSUE TITLE
Right hand navigation partially hidden on very "short" pages

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1441]
When the content on a docs page is very "short", that is doesn't have a lot of content, the right hand navigation is partialy obscured.  This means the "edit this page" link looks like this (see below).  When your browser window is decently tall enough (>1000px), there's no amount of scrolling that can fix it - there is no off screen content to scroll to!

![image](https://github.com/medic/cht-docs/assets/8253488/5642c736-e514-4942-9eba-322749f14f48)

I suspect that most visitors on a laptop may not ever notice this  because they keep their window height under <1000px or they're just reading longer content where the issue doesn't manifest (or they're just not as pedantic as me!).

Steps to reproduce:
1. go to a "short" page like [contib to docs](https://docs.communityhealthtoolkit.org/contribute/docs/)
2. make your browser window as tall as you can - you can also zoom out in your browser to shrink the text and thus the height
3. note the upper right navigation is partially obscured.

Here's a video showing this effect on the [core code contib page](https://docs.communityhealthtoolkit.org/contribute/code/core/):

https://github.com/medic/cht-docs/assets/8253488/8d2d6cee-8462-4382-9a91-b43c6c8f05ef

**Comment by esthermmoturi** [comment]
Hey @mrjones-plip , I have not been able tor replicate the issue. I zoomed out to about 33% and placed full screen on my window. Is there anything else I am missing? Does the issue still manifest for you?
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/43755711-3cd9-41e2-9490-d4b9f415b184">

**Comment by mrjones-plip** [comment]
@esthermmoturi - sweet! Looks like a recent-ish update fixed it.  Thanks for circling back to this issue to check on it!
