### ISSUE TITLE
Update documentation for model deployment

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-docs#1447]
Currently, we create project-specific models by branching off the `main` branch. 

For some projects, the data models should be private and maintained by that particular project.

Design and document a process for allowing Product to update the core models in cht-pipeline and app devs to update the project models without breaking either.

[Related Slack thread](https://medic.slack.com/archives/C02N5UGRABF/p1711990110484719).

**Comment by andrablaj** [comment]
@witash I noticed this issue was moved to `Done`. Can you please close the ticket (if `Done`) and link the PR where the doc was added? Thanks!

**Comment by witash** [comment]
moving back to in progress, to track investigating whether we can keep base models and proejct models seaprate, and because the current solution for private models (github personal access token) may not be the best

**Comment by witash** [comment]
related PR https://github.com/medic/cht-docs/pull/1394 (for dbt model creation but also has deployment)
additonal details (versioning) might come from https://github.com/medic/cht-pipeline/issues/148
