### ISSUE TITLE
Improve 'Architecture of CHT Instances'

### ISSUE THREAD

**Issue by SCdF** [medic/cht-docs#146]
Page: /core/overview/architecture/
Version: 2020-06-04 16:16:18  1200  1200
---

The architecture diagram is no longer accurate. It now looks like this:

![image](https://user-images.githubusercontent.com/583851/84517321-0a547d00-acc7-11ea-8aa1-838a722bf10a.png)

In text form:
 - Are we sure that gateway talks to rapidpro? Or do we here mean either medic-gateway or any other sms aggregator?
 - sentinel talks to couchdb through api not directly
 - couch2pg talks to couchdb through api not directly

**Comment by MaxDiz** [comment]
@garethbowen do you own this diagram? (or do you know who does?)

**Comment by garethbowen** [comment]
Merged.
