### ISSUE TITLE
Reorganize the sections in the development workflow page

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-docs#1517]
The current [Development workflow page](https://docs.communityhealthtoolkit.org/contribute/code/workflow/) sections do not follow the logical journey of the development workflow. For example, the `Issues` section should probably be before the `Branches` and `Commits` ones. Also, `Updating The Issue With What You Actually Did` should move before the `Code Reviews `section.

**Comment by latin-panda** [comment]
The development workflow for code contributors can have a "happy path" that is easy and fast to read (no big paragraphs). It can start with something like:

> This page guides you through the development process, from identifying a problem to releasing your solution. 

Then describe a journey, for example: 

_Identifying the Issue_

* Issues are managed in GitHub
* Create the issue in the appropriate repository (`cht-core` by default). 
* Use clear labels for **Priority** and **Type** (short list of most essential labels and when to use them) 
    * Use "Regression" label and "Affects: {{version}}" labels for .......

_Prioritization and Planning_  

(Clarify if this applies to external contributors too) 

* Once an issue is scheduled for development, it's added to the "Product Team Activities" project. 
* Each column in the project represents the state of the issue (list of states and when to use them)
    * **Todo:** Prioritized and ready for development. 
    * **In progress:** Actively being worked on (development, design, testing, etc.).

_Development_

* **Branching:** Create a branch following naming guidelines (e.g. `<issue-number>-<issue-description>`).
* **Commits:**
    * Push commits at least daily to a remote repository.
    * Follow the commit message format  (type, description, optional details) ( table of commit format prefixes )
    * Squash and merge commits to keep a clean history.

_Code Review and Testing_

* **Pull Requests:**
    * Create a Draft Pull Request for collaboration and discussion.
    * Convert to "Ready for review" when complete.
    * Include the issue number, description, screenshots/videos of tests, and self-review notes.
    * Assign one reviewer (developer) and optionally another for specific expertise.
    * Coordinate with a QA engineer when needed.
* **Review Process:**
    * Reviewers should provide feedback within 24 business hours.
    * Address reviewer feedback and ensure GitHub Actions pass.

_Merging and Release_

* **Merge:** Use "Squash and merge" to combine commits into one.
* **Backporting:** If needed, cherry-pick the merged commit to relevant release branches.
* **Documentation:** Update documentation (CHT Docs, README files, code comments).
* **Testing:** Ensure all tests (unit, e2e, integration) pass.
* **Release Milestone:** Add the issue to the appropriate release milestone.
* **Marking Done:** Update the issue status to "Done" when all criteria are met.

**Comment by latin-panda** [comment]
If something needs a deeper dive into the topic, that would be better on a separate page, and keep this one short/straightforward.
