### ISSUE TITLE
Remove all mentions of "CHT Pipeline"

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-docs#1521]
The "CHT Pipeline" brand does no make sense on its own and should in all situations be removed. This should be cleaned up before announcing the production ready release of CHT Sync so there is no confusion.

The product is "CHT Sync" which is broken down into several components which have internal names and repositories which do not need to be changed (eg: the cht-pipeline repository), but for anyone new to the community it's confusing to have multiple names for the same thing.

**Comment by Phil-Mwago** [comment]
Re-opening this as there still is mention on CHT Pipeline on the doc site. I will link PRs here.

**Comment by Phil-Mwago** [comment]
@njuguna-n, @witash & @lorerod there is reference to CHT pipeline in some [code snippets](https://docs.communityhealthtoolkit.org/apps/guides/data/analytics/production/) that we need to remove, how do you propose going about this?

**Comment by njuguna-n** [comment]
@Phil-Mwago the reference is for adding the `cht_pipeline_branch_url` which is still needed to access the models to be run. Do you propose we rename this environment variable?

**Comment by witash** [comment]
I don't think we need to remove or rename internal references to cht-pipeline in the code. It does still exist as a github repository, just not an independent project/brand, so references to cht-pipeline as a repository I think are ok.
