### ISSUE TITLE
hierarchy images squished in Firefox,  OK in chrome.

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1525]
[hierarchy images](https://docs.communityhealthtoolkit.org/apps/concepts/hierarchy/#places) render  squished in Firefox but seem OK in chrome.  I rolled my local dev site back to a commit from a ~year ago and it was still an issue :thinking: 

![image](https://github.com/user-attachments/assets/d7293ee6-00d7-4929-a2e4-60561c5e7935)

Gareth [mentions](https://medic.slack.com/archives/CUXB9SVT5/p1725544077838019?thread_ts=1725543931.988219&cid=CUXB9SVT5): 

> The foreignObject parent height is hardcoded differently in each browser...

**Comment by esthermmoturi** [comment]
Works in Firefox 130.x but not 131.x.

**Comment by tmatheas** [comment]
@esthermmoturi I couldn't find the issue in Firefox 131. Can you share me the steps to reproduce the issue ?

**Comment by mrjones-plip** [comment]
@tmatheas - thanks for checking in on this ticket! I also can't reproduce it in FF 131.  I suspect [the fix](https://github.com/medic/cht-docs/issues/1547) to remove `\n` may have fixed it?

given it's now working - closing this issue
