### ISSUE TITLE
Replace old CHT logo on docsite

### ISSUE THREAD

**Issue by esthermmoturi** [medic/cht-docs#1553]

**Comment by tmatheas** [comment]
@esthermmoturi Can you explain this issue and assign it to me

**Comment by esthermmoturi** [comment]
In pages like [this](https://docs.communityhealthtoolkit.org/building/guides/integrations/openmrs/), we have the old CHT logo rather than the new one. There are a couple of others that need to be replaced. Is this something you'd like to take up @tmatheas ?

**Comment by tmatheas** [comment]
@esthermmoturi Yes you can assign me this.

**Comment by esthermmoturi** [comment]
[Here](https://github.com/medic/cht-core/blob/master/api/src/resources/logo/cht-logo.png) is the new CHT Logo

**Comment by esthermmoturi** [comment]
I have assigned you the issue, kindly tag me to review the PR once it's ready

**Comment by tmatheas** [comment]
sure please add `hacktoberfest` tag to this issue.

**Comment by tmatheas** [comment]
@esthermmoturi I have changed the logo. Is this correct ?
![short-logo](https://github.com/user-attachments/assets/ce0b5842-bd83-4727-865f-7d2daf0999ad)

**Comment by esthermmoturi** [comment]
Can we use this one instead, I realized that the one I sent earlier is not descriptive. Doesn't have 'Community Healthtoolkit'

**Comment by esthermmoturi** [comment]
[This](https://docs.communityhealthtoolkit.org/building/guides/integrations/rapidpro/) page also has the old logo.

**Comment by tmatheas** [comment]
@esthermmoturi I have sent you 2 images, which one shall we use. I will raise the PR. Can you please add the tag `hacktoberfest` to the issue. And once PR is reviewed and merged you can close the issue with the tag `hacktoberfest-accepted`

**Comment by tmatheas** [comment]
> [This](https://docs.communityhealthtoolkit.org/building/guides/integrations/rapidpro/) page also has the old logo.

Sure will update that too

**Comment by esthermmoturi** [comment]
Kindly use the second image with the [descriptive logo](https://github.com/medic/cht-core/blob/master/api/src/resources/logo/cht-logo-light.png).

**Comment by esthermmoturi** [comment]
Do you want me to add `hacktoberfest` to the issue description? Also could you provide more context on the same for anyone else who will stumble on this issue?

**Comment by tmatheas** [comment]
@esthermmoturi Please review this #1588 . And once PR is reviewed and merged you can close the issue with the tag `hacktoberfest-accepted`

**Comment by tmatheas** [comment]
Thanks @esthermmoturi. Mention the tag `hacktoberfest-accepted` in issue too.

**Comment by tmatheas** [comment]
@mrjones-plip Can you assign `hacktoberfest-accepted` to this issue and close the issue.
