### ISSUE TITLE
Components not shown on 'Component Library'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#1560]
Page: /design/components/
Version: 2023-05-19 14:14:18  0000 UTC
---

The components in the Design System's Component Library show code, instead of the graphical representations of each component:

![image](https://github.com/user-attachments/assets/2540d1a9-891f-4d66-854a-cf9649c410ae)

**Comment by esthermmoturi** [comment]
Hey @n-orlowski , is this an issue you would like to have a look at?

**Comment by esthermmoturi** [comment]
Closed by #1579
