### ISSUE TITLE
production hosting docs:  split between docker vs k8s, deprecate swarm 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1566]
This is what we have now:

**4. x**
* Data migration to 4.x
* Self Hosting
   * Single Node - Docker
   * Multiple Nodes - Docker
   * Multiple Nodes - k3s
* App Developer Hosting
* TLS Certificates
* Logs
* Backups

This is what I think we should move to in the next few days - we can wait on writing the Medic EKS one.  I'll be happy to draft all the content:

* Data migration to 4.x
* App Developer Hosting
* Production Hosting
   * Docker Intro (_doesn't exist_)
       * Single Node - Docker
       * DEPRECATED: Multiple Nodes - Docker
       * TLS Certificates
       * Logs
       * Backups
   * Kubernetes Intro (_doesn't exist_)
       * Intro to how to run k8s (_doesn't exist_)
       * Example: k3s on VMware
       * Example: EKS at AWS (_doesn't exist - how Medic Hosts_)

**Comment by jkuester** [comment]
Also might be worth capturing this on https://github.com/medic/cht-tech-radar-contributors (what we are using going forward and what we are not using).

**Comment by mrjones-plip** [comment]
Oh - good thinking @jkuester !

I _think_ the only change is to add "Docker Swarm" to "Stop", yeah? We still very much support Docker and k8s and the rest of the tech mentioned above.

**Comment by esthermmoturi** [comment]
I see that we are renaming from _Self-hosting_ to _Production hosting_, which is great. Is there any difference we have observed in various deployments between the two(if there is any difference at all), that we would like to highlight?

**Comment by mrjones-plip** [comment]
Good question @esthermmoturi !  For a long time Medic hosted all CHT instances and anything else was "self hosting".  

As we move more and more toward community centric focus, I think the proper long term distinction is "development" vs "production" and they're all "self" hosted regardless if they're on a big server under your desk or in the cloud.

**Comment by mrjones-plip** [comment]
fixed in 1568#
