### ISSUE TITLE
Remove ToC as it is a duplication of the side bar

### ISSUE THREAD

**Issue by esthermmoturi** [medic/cht-docs#1586]
https://docs.communityhealthtoolkit.org/building/guides/privacy/policy/

**Comment by tmatheas** [comment]
@esthermmoturi Just need to remove this section right ?

<img width="946" alt="image" src="https://github.com/user-attachments/assets/2722b84f-7271-4c19-8a3a-42b020a5fddd">

**Comment by tmatheas** [comment]
Hi @esthermmoturi I have fixed this issue. And [here](https://github.com/medic/cht-docs/pull/1592) is the PR for the issue. Please add me to the issue. Add `hacktoberfest` tag to the issue and PR. Also once reviewed and merged. Please add a tag `hacktoberfest-accepted` and close the issue

**Comment by tmatheas** [comment]
> Hi @esthermmoturi I have fixed this issue. And [here](https://github.com/medic/cht-docs/pull/1592) is the PR for the issue. Please add me to the issue. Add `hacktoberfest` tag to the issue and PR. Also once reviewed and merged. Please add a tag `hacktoberfest-accepted` and close the issue

@mrjones-plip You can also review this !!

**Comment by tmatheas** [comment]
@mrjones-plip Can you assign `hacktoberfest` and `hacktoberfest-accepted` to this issue
