### ISSUE TITLE
Move CHT Sync & Interoperability documentation

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-docs#1595]
Per [the discussion in Slack](https://medic.slack.com/archives/C03SP4KRVEX/p1728040996902819):

- [x] Move the [CHT Sync section](https://docs.communityhealthtoolkit.org/building/guides/data/analytics/) (`building/guides/data/analytics/`) under [Hosting](https://docs.communityhealthtoolkit.org/hosting/) (`hosting`). 
- [x]  Move [Building Interoperability with FHIR systems documentation](https://docs.communityhealthtoolkit.org/building/guides/integrations/fhir/)(`building/guides/integrations/fhir/`) under a newly created _Interoperability_ section (maybe under `building/guides/integrations`)?

**Comment by Phil-Mwago** [comment]
Complete.
