### ISSUE TITLE
remove multi-node compose docs, mention resharding

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1597]
[These docs](https://docs.communityhealthtoolkit.org/hosting/4.x/production/docker/multiple-nodes/) should be removed - folks should use k8s (and friends) for multi-node

Since this will remove the warning "don't use swarm" - we should prob add mention of this somewhere TBD helpful.

while were in there we should add a link about resharding as it can improve both single and multi-node performance on either compose or k*s based instances. this is because 1shard = 1 core so if you have more cores you can get better performance by adding more shards.

**Comment by garethbowen** [comment]
CouchDB docs here: https://docs.couchdb.org/en/stable/cluster/sharding.html#splitting-shards
