### ISSUE TITLE
Create a guide for voice and tone of documentation

### ISSUE THREAD

**Issue by n-orlowski** [medic/cht-docs#1628]
The [voice and tone](https://developers.google.com/style/tone) across CHT documentation should be [inclusive](https://developers.google.com/style/inclusive-documentation) and [accessible](https://developers.google.com/style/accessibility) to it's audience. 

Create a guide of best practices for contributing.

**Comment by esthermmoturi** [comment]
I am working on [this](https://docs.google.com/document/d/1RRo4Io64idl5zYryWOc3do3ogUsZ1mlM8zIX0tLvRKw/edit?usp=sharing) page template. It is still WIP and I hope to add more items.

**Comment by n-orlowski** [comment]
Thanks @esthermmoturi ! This is more about how to write for our different audiences and examples of the details to go into for each - we can align on this a bit later

**Comment by n-orlowski** [comment]
[Draft here](https://docs.google.com/document/d/19Da3GaoRvbDbKU32teXzO0X39h47dxPAbgmszSbNjUg/edit?tab=t.0)
