### ISSUE TITLE
Remove "Beta" from cht-docs repo description

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#164]
We're outa beta, right? New site has been live for a week, so I figure so ;)

Request is to change [this repo's description](https://github.com/medic/cht-docs) from:

> Beta documentation site for the Community Health Tookit https://docs.communityhealthtoolkit.org

And remove "Beta" so that it then reads:

> Documentation site for the Community Health Tookit https://docs.communityhealthtoolkit.org

I also hope this is an easy win for someone and not a premature and pedantic ticket (though I guess it could be both).

**Comment by garethbowen** [comment]
Done. Thanks!
