### ISSUE TITLE
Incorrect link to code style guide, goes to docs style guide instead

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#165]
In the old docs site, we had a [Development Workflow](https://github.com/medic/medic-docs/blob/master/development/workflow.md) page that said:

> Where possible, follow our coding [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md).

Note that the link to `style guide` goes to a page that tells you the style we prefer our **code** to be written in.

On the new site, we have the same page title [Development Workflow](https://docs.communityhealthtoolkit.org/core/process/workflow/) with the same sentance:

> Where possible, follow our coding [style guide](https://docs.communityhealthtoolkit.org/docs-style-guide/).

However the link for `style guide` does not go to a page that tells you the style of our code, but the style of our **docs**.

I think the fix here is to create a new `style-guide.md` page in this repo (cht-docs), or find where it was already created, and update the link for `style guide` to go this page. Doing a [quick search](https://github.com/medic/cht-docs/search?q=style-guide.md&type=Commits), I didn't find it, so I suspect it needs to be created.

**Comment by garethbowen** [comment]
The coding style guide still exists here: https://docs.communityhealthtoolkit.org/core/process/style-guide/

Link updated in PR.

**Comment by garethbowen** [comment]
This is being addressed as part of https://github.com/medic/cht-docs/pull/166

**Comment by mrjones-plip** [comment]
Cools - thanks for the updates! Will close this one as it's now a dupe per your comment.
