### ISSUE TITLE
Improve 'Antenatal Care Reference App'

### ISSUE THREAD

**Issue by helizabetholsen** [medic/cht-docs#167]
Page: /apps/examples/anc/
Version: 2020-06-09 13:34:24 -0500 -0500
---

I'm wondering if we want to include documentation for ANC as a use case similar to the issues for our other priority CHT use cases, see #156 #157 #158 as examples. 

cc @MaxDiz

**Comment by MaxDiz** [comment]
- Review default config of reference app to see what workflows are currently configured (FP, ICCM, and covid assessment may have been added)

- Decide whether we still want an ANC only reference app to be available, and if we do, update the installation instructions and make sure there’s a link to a repo that has just the ANC reference app.

- Decide whether we want a new docs page for what’s currently in the default config. If so, it would probably benefit from a new name like “Standard Reference App” or “Integrated Care in the Community Reference App” or something like that.

- The current ANC reference app page on the docs site points to the easy installation instructions (off the docs site) - this should be redirected to the doc site 

- Make it clear that the ANC Reference app is referred to elsewhere as “default config”

**Comment by MaxDiz** [comment]
relevant presentation: https://docs.google.com/presentation/d/1EdB3jCiH_D_IYdQgP43MWwfOZWUJqiM_a5k9Bhh-3hQ/edit#slide=id.p3

**Comment by MaxDiz** [comment]
https://github.com/medic/cht-docs/pull/239

**Comment by MaxDiz** [comment]
@abbyad what do you think about connecting the ref app cofig to a demo app deployment in the playstore and adding to the doc site for download? It would nice to provide an easy way for users to experience the app after they've read through the documentation.

**Comment by abbyad** [comment]
We had considered that originally and decided instead to have a separate demo config which showcases features and workflows more readily, eg having a task show up immediately when you do something.

It would be good to review what would be useful across difference audiences, and see how we can serve that. It may mean consolidating the CHT demo with the reference app in some way.

**Comment by MaxDiz** [comment]
merged - thanks for all of the iterations on this ticket. It will serve as a good template for other documentation
