### ISSUE TITLE
Improve 'Documentation Workflow': links in the upper right hidden too often?

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#176]
Page: /contribute/docs/workflow/
Version: 2020-06-22 23:08:51 -0400 -0400
---

Heya!  I've been using the new docs site for a week and after @abbyad's post in slack about the new workflow, I checked out this page.  It reads (emphasis mine): 

> Anyone can contribute to CHT documentation by opening an issue in the cht-docs repo or by using the “Edit this page” or “Create documentation issue” **links in the upper right corner of your window**

I literally had no idea these links in the upper right existed because I do so much reading on mobile/tablet and, apparently, on many browser window narrower than 1200px. At <1200px wide, these links simply disappear (yes @SCdF, I even checked outside my dogmatic "no javascript allowed" browser ;)  .  Given how helpful they are, maybe we should consider smooshing them into a hamburger menu instead of the `display: none!important;` treatment they get now? 

This might be a super corner case (silly developers wanting a 3 up display of browsers on one screen), but I see we also run Google Analytics which can tell us how many esoteric users like me there actually are.  We can even show stats on window size vs screen size if wanna [get real fancy](https://css-tricks.com/google-analytics-can-show-screen-resolution-%E2%89%A0-browser-window/)!

Feel free to close as "love ya, won't fix" ;)

**Comment by abbyad** [comment]
Glad you brought this up! It's not clear what the best way would be to handle that. Would help in the short term to mention in documentation that those links are available when viewing in desktop mode only?

**Comment by mrjones-plip** [comment]
And, oh! i see on responsive (~750px) we actually collapse the left hand side navigation into a right hand side hamburger menu. Dishy indeed! Maybe we could double down on this and first collapse the edit links into that and then append the navigation into it too?  

Otherwise, yeah, short term saying that these links are available on desktop would a good tip for sure. One step further would be to say something like, "only in desktop mode with a wider browser window". But admittedly that last part may be more confusing that clarifying.

**Comment by abbyad** [comment]
Thanks, we can look at improving that. The main structure and collapsing is handled by the [Docsy theme](https://github.com/google/docsy/) that we are using, so this would be good feedback for maintainers at Google!

**Comment by mrjones-plip** [comment]
Interesting! I just spent a bit too long poking around on the [docsy repo](https://github.com/google/docsy) ;) 

I do see we have a [partial](https://github.com/medic/cht-docs/blob/master/layouts/partials/page-meta-links.html) that defines the content in question, maybe there's a way we can include it below the "Feedback" section and just hidden when >1200px? I suspect y'all have thought on this some and likely isn't that productive to dwell on this toooo much.  That said, if there's been some friction on this already, happy to research/submit bugs on our behalf!

**Comment by abbyad** [comment]
@mrjones-plip is this what you were imagining? It would show up only when the right toc section is hidden, which happens when not in a `xl` size. 

![image](https://user-images.githubusercontent.com/789512/85593982-86c75400-b615-11ea-962a-102ca806065e.png)

**Comment by mrjones-plip** [comment]
Yes, that would be a perfect win win solution in my opinion! 

Oh...but wait, not in a `x1` size, meaning for some (all?) mobile UIs wouldn't show it?  Any reason to hide it from them?

**Comment by abbyad** [comment]
Ah, just to clarify... my `xl` = `XL`. So it will show on everything but e`X`tra `L`arge, since the links are shown on the right side in that display size.

**Comment by mrjones-plip** [comment]
Ah, perfect, thanks for gently reminding me that `xl != x1` ;)  I was thinking of `(min/max)-resolution` [trickery](https://developer.mozilla.org/en-US/docs/Web/CSS/resolution) where the default is something like `1x` ;)
