### ISSUE TITLE
Update style guide & content to not use links on titles, add "read-more" option to "see-also" shortcode

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#178]
**Update:** we're merging #205 into this ticket after it was already under way.  This is because `read-more` and `see-also` shortcodes are identical except for their prefix.

----

### No Links in titles

On the [home page](https://docs.communityhealthtoolkit.org/) and on the [architecture page](https://docs.communityhealthtoolkit.org/core/overview/architecture/) we use some titles (`###`, but could be `##` too) as links.  Here's a list as of now (below).  I think this is bad UX and we shouldn't do this. The reason is that these links get rendered in the TOC and are expected to jump you to that spot lower in the same page. Instead, the TOC links take you to a whole other page.

Proposal - update the the [style guide](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/) to call out to not do this and remove the instances below (and any more that may have cropped up since).  Instead of linking the `h3` we should add a `Read More` text at the end of the paragraph and link that text.

```
content/en/core/overview/architecture.md:### [CouchDB](http://couchdb.apache.org)
content/en/core/overview/architecture.md:### [api](https://github.com/medic/medic/tree/master/api)
content/en/core/overview/architecture.md:### [sentinel](https://github.com/medic/medic/tree/master/sentinel)
content/en/core/overview/architecture.md:### [PostgreSQL](https://www.postgresql.org)
content/en/core/overview/architecture.md:### [cht-core](https://github.com/medic/cht-core)
content/en/core/overview/architecture.md:### [medic-android](https://github.com/medic/medic-android)
content/en/core/overview/architecture.md:### [medic-gateway](https://github.com/medic/medic-gateway)
content/en/core/overview/architecture.md:### [medic-collect](https://github.com/medic/medic-collect)
content/en/core/overview/architecture.md:### [medic-conf](https://github.com/medic/medic-conf)
content/en/_index.md:### [Why the CHT?]({{% ref "why-the-cht" %}})
content/en/_index.md:### [CHT Applications]({{% ref "apps" %}})
content/en/_index.md:### [CHT Core Framework]({{% ref "core" %}})
content/en/_index.md:### [Design System]({{% ref "design" %}})
```

While we're in the style guide, we should be sure to avoid one of the problems originally found in this ticket which was bad links with `HAHAHUGOSHORTCODE` as the destination. The ticket has since been repurposed, but one of the comments before was:

> I didn't [find any instances](https://github.com/medic/cht-docs/search?q=HAHAHUGOSHORTCODE-s7-HBHB&unscoped_q=HAHAHUGOSHORTCODE-s7-HBHB) of `HAHAHUGOSHORTCODE-s7-HBHB` in our code, so something smelled a bit fishy. Turns out that hugo generates this when it has [problems parsing the headers](https://github.com/gohugoio/hugo/issues/6081) with in the file it's on. The fix is to either remove the link from the href to change this `### [Why the CHT?]({{< ref "why-the-cht" >}})` to simply this `### Why the CHT?`, or to use a safe syntax `### [Why the CHT?]({{% ref "why-the-cht" %}})`.  

_NB - this `<` -> `%` change has since been done in #189 ._

### Extend `see-also` to offer `read-more`

Per the discussion below, we'd like to offer the `read-more` prefix as a solution to linking titles.  This will mean extending the existing [`see-also` template](https://github.com/medic/cht-docs/blob/master/layouts/shortcodes/see-also.html#L14).

### Fix hanging anchors

Every time we use an `see-also` shortcode, there's always a trailing `#` on the link.  For example on the [workflows page](http://docs.communityhealthtoolkit.org/apps/concepts/workflows/) the  `see also` on "SMS Messaging" correctly has a `#` in the URL because the markdown has an anchor:

```
{{% see-also page="apps/reference/app-settings" anchor="sms-workflows" title="Defining SMS Workflows" %}}
```

the resulting URL is correctly `https://docs.communityhealthtoolkit.org/apps/reference/app-settings/#sms-workflows`

However, the one above for "Tasks" does not:

```
{{% see-also page="apps/reference/tasks" title="Defining Tasks" %}}
```

but  the URL still has an anchor `https://docs.communityhealthtoolkit.org/apps/reference/tasks/#`.

This is because the if/else logic in the [`see-also` template](https://github.com/medic/cht-docs/blob/master/layouts/shortcodes/see-also.html#L14) always assumes there's an anchor.

**Comment by mrjones-plip** [comment]
I didn't [find any instances](https://github.com/medic/cht-docs/search?q=HAHAHUGOSHORTCODE-s7-HBHB&unscoped_q=HAHAHUGOSHORTCODE-s7-HBHB) of `HAHAHUGOSHORTCODE-s7-HBHB` in our code, so something smelled a bit fishy. Turns out that hugo generates this when it has [problems parsing the headers](https://github.com/gohugoio/hugo/issues/6081) with in the file it's on.  I suspect maybe because we have `### [Why the CHT?]({{< ref "why-the-cht" >}})` as the header instead of simply `### Why the CHT?` ?  I'm new to hugo, but I'll try the fix locally real quick and see what I find.

**Comment by mrjones-plip** [comment]
Hrm - so changing the links from `### [Why the CHT?]({{< ref "why-the-cht" >}})` to `### [Why the CHT?]({{% ref "why-the-cht" %}})` works, but not as we intended I don't think.  With this change the behavior is that while clicking the actual inline `h3` does take to the `href` destination, so does TOC link.  That is, the TOC link goes from being `/#why-the-cht` to being `/why-the-cht`. I think this makes for bad UX. If there's no other fix I propose unlinking the `h3` so the TOC works as expected and uniformly on the site and then adding an annoyingly repetitive `read more!` at the end of each of the sections :roll_eyes:

**Comment by mrjones-plip** [comment]
Thinking a little more holistically, we can check every document that uses links in headers with `grep  -r "^#" content/en/|grep ']('` . The results are:

```
content/en/core/overview/architecture.md:### [CouchDB](http://couchdb.apache.org)
content/en/core/overview/architecture.md:### [api](https://github.com/medic/medic/tree/master/api)
content/en/core/overview/architecture.md:### [sentinel](https://github.com/medic/medic/tree/master/sentinel)
content/en/core/overview/architecture.md:### [PostgreSQL](https://www.postgresql.org)
content/en/core/overview/architecture.md:### [cht-core](https://github.com/medic/cht-core)
content/en/core/overview/architecture.md:### [medic-android](https://github.com/medic/medic-android)
content/en/core/overview/architecture.md:### [medic-gateway](https://github.com/medic/medic-gateway)
content/en/core/overview/architecture.md:### [medic-collect](https://github.com/medic/medic-collect)
content/en/core/overview/architecture.md:### [medic-conf](https://github.com/medic/medic-conf)
content/en/_index.md:### [Why the CHT?]({{< ref "why-the-cht" >}})
content/en/_index.md:### [CHT Applications]({{< ref "apps" >}})
content/en/_index.md:### [CHT Core Framework]({{< ref "core" >}})
content/en/_index.md:### [Design System]({{< ref "design" >}})
```

Checking the `architecture.md` file, I see all the TOC links work, but as direct links to 3rd party pages, not as anchors to content on the same page as a user would expect.

**Comment by mrjones-plip** [comment]
@abbyad  - for when you get back from vacation, a proposal to update things.  Hope it was OK to repurposed this ticket after we fixed stuffs up on #184 !

**Comment by abbyad** [comment]
Good call! It seems somewhat clean to have the links on the headers, but we don't want the sidebar to link externally instead of to the page content -- I would consider that to be a bug. As you mention, we should fix all header links with "read more" links instead, and add this scenario to the style guide.

**Comment by mrjones-plip** [comment]
this is live now - thanks again!

FYI @n-orlowski  - "Read More" abounds on [home page](https://docs.communityhealthtoolkit.org/)! :smile:
