### ISSUE TITLE
Improve 'Targets'

### ISSUE THREAD

**Issue by shreyakb** [medic/cht-docs#183]
The note in the **Supervisor View** section is eating into the image.

I'm viewing this on a Chrome browser, Version 83.0.4103.116 

![image](https://user-images.githubusercontent.com/7915295/85740763-831ff400-b71f-11ea-9141-791483ed9aa4.png)

Page: /apps/features/targets/
Version: 2020-06-16 12:45:27 -0400 -0400
---

**Comment by MaxDiz** [comment]
merged
