### ISSUE TITLE
Error 404 on some link redirects

### ISSUE THREAD

**Issue by rosteve** [medic/cht-docs#184]
I've found some couple of 404's in some link redirects:

- [Contact and User Management - Part 1](https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-1/) : The link on " manipulating contacts and their associated documents using medic conf" goes to `creating-and-managing-users-and-contacts-with-medic-conf.md` is broken. Full destination URL  `https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-1/creating-and-managing-users-and-contacts-with-medic-conf.md` 
- [Contact and User Management - Part 1](https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-1/) and [Contact and User Management - Part 2](https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-1/) : The same link on both pages for "How to set up a CHT local configuration environment" goes to `setting_up_local_configuration_environment.md` is broken. Full destination URL   `https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-1/setting_up_local_configuration_environment.md`
- [Contact and User Management - Part 2](https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-2/) : The link on "key concepts" goes to `creating-and-managing-users-and-contacts.md#brief-overview-of-key-concepts` is broken. Full destination  URL `https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-2/creating-and-managing-users-and-contacts.md#brief-overview-of-key-concepts`
- Searching for [introduction](https://docs.communityhealthtoolkit.org/search/?q=introduction#gsc.tab=0&gsc.q=introduction&gsc.ref=more%3Adocumentation&gsc.sort=) or community health toolkit brings results that includes this broken link - (see the screenshot below)`https://docs.communityhealthtoolkit.org/docs/application_development/guides/from_scratch/001_introduction.html`
[
![Screen Shot 2020-06-26 at 12 42 47 PM](https://user-images.githubusercontent.com/6769401/85844262-1ce0b300-b7ab-11ea-8a0b-2413f7661764.png)
](url)

cc: @MaxDiz

**Comment by mrjones-plip** [comment]
@rosteve  - thanks so much for filing the issue on the broken links! I filled in some details on where the links are so they're easier for the team to resolve, I hope that's OK.  However, I could find the page with a broken link to `001_introduction.html`, the first item you listed.  When you get a sec, could give us the URL for the docs page that links to this page so we can fix it?  Thanks thanks!

**Comment by mrjones-plip** [comment]
@abbyad  & @MaxDiz  - maybe we should add a link checker to the GH Action we have for PRs to avoid this sorta thing? I'm not very familiar with either hugo or actions, but I see [such things exist](https://github.com/marketplace/actions/hugo-broken-link-check). Happy to help research/deploy (on another ticket obvs.) if y'all want some newbie love ;)

**Comment by mrjones-plip** [comment]
@rosteve  - Oh i see!! Thanks so much for extra description and screen shots.  Super helpful. @abbyad  - That feels like a search freshness issue, which I assume is the cost of having more feature rich google results instead of using built in JS hugo tools.  I'll defer to y'all how to handle that.

**Comment by mrjones-plip** [comment]
It was a quiet afternoon and no one  was around the office, so I took a looksee at some automated 404 checking tools.  [Linkchecker](https://github.com/linkchecker/linkchecker) looks great! (not this [deprecated one](https://github.com/wummel/linkchecker) FYI). I ran it locally against my dev instance and found:
* We have 43 404s including the 3 above, excluding search resutls
* we should run a low thread count to avoid GH tarpitting and 429ing (`-t5`)
* we should check outbound links (`--check-extern`)
* we have ~28902 links in ~1373 URLs (nice high water mark which will only go up!)
* it took ~6 min to run w/ 5 threads using: `linkchecker http://192.168.68.40:1313 -t5 --check-extern -o csv> ../docs.404.csv`

While I'm not sure if A) we're going to automate this on a per PR basis in GH or B) if this is the tool we're gonna go with if we do, I thought it helpful to document my experience. If we're serious about this, we can spin this info into a new ticket. Attaching resulting .csv (but actually the "c" stands for "semicolon" ;)
[docs.404.Jun.26.2020.zip](https://github.com/medic/cht-docs/files/4839719/docs.404.Jun.26.2020.zip)

**Comment by abbyad** [comment]
This is very helpful! We should definitely run this periodically, if not as part of the build process (worth opening a separate issue). In the meantime we can fix the broken links as part of this issue.

**Comment by mrjones-plip** [comment]
@rosteve  - the 3 non-search links are fixed up (as well as a TON of others ;). Thanks again for filing the ticket!

I see closing the PR closed this issue, which maybe shouldn't be right given we still have a problem with the search results being stale now 4+ days later?  I'll defer to @garethbowen  and @abbyad  if we should re-open this ticket or create a new one to track bad search results.

**Comment by mrjones-plip** [comment]
@rosteve  - tracking bad search results in #197
