### ISSUE TITLE
Reference Document for SMS "reminder" : app_setting.json

### ISSUE THREAD

**Issue by ashish-medic** [medic/cht-docs#191]
Currently, cht-docs is missing the detail documents for "reminder" 
 ```
"reminders": [
    {
      "form": "",
      "text_expression": "",
      "cron": "",
      "mute_after_form_for": "",
      "message": ""
    }
  ],
```
It would be helpful if we can get information on :
- How to use `text_expression` , what are the option available for text_expression
- What is the use of `cron`
- Use of `mute_after_form_for`

**Comment by MaxDiz** [comment]
closing via https://github.com/medic/cht-docs/pull/216
