### ISSUE TITLE
Improve 'Event Based Surveillance'

### ISSUE THREAD

**Issue by shreyakb** [medic/cht-docs#194]
It would be great to add in the [EBS video](https://www.youtube.com/watch?v=LwUEJBrfDEA&feature=youtu.be) as a workflow example similar to how we've done this on the [PHC adaptations ](https://docs.communityhealthtoolkit.org/apps/examples/phc-covid/) page.

@MaxDiz 

Page: /apps/examples/ebs/
Version: 2020-06-23 07:11:13 -0700 -0700
---

**Comment by MaxDiz** [comment]
merged
