### ISSUE TITLE
Improve 'Contact Tracing'

### ISSUE THREAD

**Issue by shreyakb** [medic/cht-docs#195]
It would be great to add in the Contact tracing demo video as a workflow example similar to how we've done this on the [PHC adaptations ](https://docs.communityhealthtoolkit.org/apps/examples/phc-covid/) page.

@MaxDiz 

Page: /apps/examples/contact-tracing/
Version: 2020-06-05 17:21:35 -0700 -0700
---

**Comment by MaxDiz** [comment]
merged
