### ISSUE TITLE
Prepare Self Hosting System Link broken or not publicly accessible

### ISSUE THREAD

**Issue by ronna** [medic/cht-docs#196]
The [Prepare Self Hosting System ](https://github.com/medic/medic-infrastructure/tree/master/self-hosting/prepare-system) link is broken or not publicly accessible under the [Follow README & Run scripts:](https://docs.communityhealthtoolkit.org/apps/guides/hosting/ec2-setup-guide/#3-provision-docker-server)

(The link might not be publicly accessible - reading through the Github issues, I have noted that medic-infrastructure repo is not publicly accessible.)

**Comment by MaxDiz** [comment]
Thanks @ronna for the feedback. We are in the process of updating the self-hosting guidance (#64). Were you able to complete your current hosting setup?

**Comment by MaxDiz** [comment]
Readme and run scrips have been made public here: https://github.com/medic/cht-infrastructure/tree/master/self-hosting/prepare-system

**Comment by MaxDiz** [comment]
fix merged
