### ISSUE TITLE
description of how to use '{{figure' is wrong, is also not used anywhere

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#198]
On our [docs style guide for images](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#images) we say you should include an image with the `figure` syntax:

```{{figure src="image.png" class="right col-6 col-lg-3"}}```

This is incorrect as it's missing either the `<` or the `%` to open and `>` or the `%` to close the figure per [the Hugo spec](https://gohugo.io/content-management/shortcodes/#example-figure-input).  Thus it should instead be:

```{{< figure src="image.png" class="right col-6 col-lg-3" >}}```

It's also noteworthy that we do not use the prescribed syntax anywhere in the docs site. The only occurrences of `{{` with `figure` are in our style guide telling contributors how to use it:

```
grep -r '{{[\% .]*figure' .
./public/contribute/docs/style-guide/index.html:<td><code>{{figure src=&quot;image.png&quot; class=&quot;right col-6 col-lg-3&quot;}}</code></td>
./public/contribute/docs/style-guide/index.html:<pre><code>{{figure src=&quot;image.png&quot; link=&quot;image.png&quot; class=&quot;right col-6 col-lg-3&quot;}}
./public/contribute/docs/index.xml:&lt;td&gt;&lt;code&gt;{{figure src=&amp;quot;image.png&amp;quot; class=&amp;quot;right col-6 col-lg-3&amp;quot;}}&lt;/code&gt;&lt;/td&gt;
./public/contribute/docs/index.xml:&lt;pre&gt;&lt;code&gt;{{figure src=&amp;quot;image.png&amp;quot; link=&amp;quot;image.png&amp;quot; class=&amp;quot;right col-6 col-lg-3&amp;quot;}}
./public/contribute/index.xml:&lt;td&gt;&lt;code&gt;{{figure src=&amp;quot;image.png&amp;quot; class=&amp;quot;right col-6 col-lg-3&amp;quot;}}&lt;/code&gt;&lt;/td&gt;
./public/contribute/index.xml:&lt;pre&gt;&lt;code&gt;{{figure src=&amp;quot;image.png&amp;quot; link=&amp;quot;image.png&amp;quot; class=&amp;quot;right col-6 col-lg-3&amp;quot;}}
./content/en/contribute/docs/style-guide.md:| `{{figure src="image.png" class="right col-6 col-lg-3"}}` | `<img src="image.png" width="30%" align="right">` |
./content/en/contribute/docs/style-guide.md:{{figure src="image.png" link="image.png" class="right col-6 col-lg-3"}}
```

Instead, for all our images we use the [old school markdown syntax](https://daringfireball.net/projects/markdown/syntax#img) of including an image:

```![alt text here](/path/to/image.png)```

Checking with `grep -r '\!\['  .|wc -l` i see we have ~400 instances of this and none of `figure` per grep above. We should either double down on the old school syntax and update the style guide to mention the `![` syntax and remove mention of `figure` or, um, somewhat painstakingly update all ~400 instances of how we reference images to use `figure`. I guess a more patient approach might be a "fix 'em as you find 'em".  Finally, another approach is that I suspect we could come up with some tricky `sed` or `awk` fu to carefully, globally search and replace to fix all our images.

**Comment by MaxDiz** [comment]
adding @n-orlowski as the keeper of the doc style guide

**Comment by n-orlowski** [comment]
Thanks, will update! Chatted with Marc and we're going to recommend using the figure tag for new content however using markdown syntax isn't incorrect; only want to avoid using html styling.

**Comment by mrjones-plip** [comment]
cool cool! if you want help doing any automated updates to existing markdown image links, I loves me a good recursive `sed` call challenge ;)
