### ISSUE TITLE
Improve doc site search to make it more user friendly

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#211]
Reviews from new users have highlighted confusion about the current doc site search. Eliminating the intermixing of search results from the doc site with results from outside the doc site is the largest area for user experience improvement. We discussed the potential to split search into "primary" for the doc site and "secondary" for anything CHT.

**Comment by MaxDiz** [comment]
related #197

**Comment by abbyad** [comment]
Assigning to @MaxDiz for AT

**Comment by MaxDiz** [comment]
LGTM!

**Comment by abbyad** [comment]
Thanks, closing now that it's been AT'ed and the PR has been merged.
