### ISSUE TITLE
Remote first time login feature education - v3.10

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#225]
In v3.10 we are introducing a new feature for [remote first time login](https://github.com/medic/cht-core/issues/6380). As part of this release, we should: 

- [x] Update the [remote onboarding and training](https://docs.communityhealthtoolkit.org/apps/examples/training/) example on the doc site to reflect these improvements  
- [x] Post an update to [the Forum](https://forum.communityhealthtoolkit.org/t/remote-onboarding-and-training-on-the-cht-for-covid-19/715)
- [x] Educate Deployment Team members on new capabilities, how to deploy, and troubleshooting so they can inform project partners (coordinate with @ranjuts)

**Comment by n-orlowski** [comment]
Docs update is awaiting approval for 3.10 launch and the blog post is drafted. @MaxDiz what is the process for the last item? Are we doing a call/deck like we did for 3.9 or am I following up with Ranju directly?

**Comment by MaxDiz** [comment]
Following up with Ranju directly sounds good. We should not need to create any additional ed materials beyond doc site, forum post, and regular version release blog post at the time of release. Trying to make this process a reasonable amount of work for the team :)

**Comment by n-orlowski** [comment]
@MaxDiz cool to close this issue? Discussions with the delivery team are in progress but have begun / I imagine will be ongoing post release

**Comment by MaxDiz** [comment]
yup, good to close. Excited to see this feature rolled out!
