### ISSUE TITLE
Include headers for mobile view of workflows in reference application

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#267]
In https://github.com/medic/cht-docs/pull/239 we completed an overhaul of the reference app documentation, including replacing static workflow images with HTML versions. The mobile rendering of the those HTML workflows do not currently have headers. Add headers to make them more user friendly.

example:
![image](https://user-images.githubusercontent.com/46463417/89325348-487a7700-d64e-11ea-9d86-07c2df34e264.png)

**Comment by abbyad** [comment]
With bootstrap I couldn't find an easy way to differentiate between these two screen size that are smaller than `xs`, so opted for a 45 degree turn on the arrow, which seemed to work well with both. We can revisit this later if there are concerns with it.

| Right Arrow | SE Arrow |
|---|---|
| ![image](https://user-images.githubusercontent.com/789512/89417547-ce54fb80-d6fc-11ea-9772-e6380ebe1fcc.png) | ![image](https://user-images.githubusercontent.com/789512/89439037-9b6c3100-d717-11ea-8b05-371d3c39a598.png) |

| Right Arrow | SE Arrow |
|---|---|
| ![image](https://user-images.githubusercontent.com/789512/89417603-e462bc00-d6fc-11ea-9bcb-6dd10cb0d13d.png) | ![image](https://user-images.githubusercontent.com/789512/89439199-d2dadd80-d717-11ea-9308-44bca2037560.png) |
