### ISSUE TITLE
Add new tasks tutorial

### ISSUE THREAD

**Issue by smbuthia** [medic/cht-docs#278]
Add a new tutorial that shows how to build CHT application tasks.

**Comment by mrjones-plip** [comment]
@smbuthia  - to flesh this ticket out a bit, you mean a tasks tutorial that's in addition to [the existing one](https://docs.communityhealthtoolkit.org/apps/tutorials/tasks/)? I ask b/c I've been updating the docs while working on the [MNCH reference app](https://github.com/medic/cht-core/issues/6727) and would love to help test/proofread a new tutorial but wanted to ensure we're not duplicating any existing efforts.

**Comment by smbuthia** [comment]
@mrjones-plip the existing one was in reference to this issue (I'll go ahead and close this @kitsao). The proofreading/testing is really appreciated. 👍
