### ISSUE TITLE
Documentation on data that can be accessed and used in forms would be helpful. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-docs#297]
Forms have access to data that comes from the app. I do not believe we have any docs on what is actually available to forms. A few examples are shown below. I'm not sure of all the data that is passed to a form so this list is not exhaustive. 

string | contact_id 
string | facility_id
string | name

Lots of forms use PLACE_TYPE to determine the contact type.

We have meta data available as well for things like start and end of form

**Comment by jkuester** [comment]
This has also been bugging me for awhile. I have collected some additional information that I want to leave it here for myself or anyone else that has a chance to pick this issue up and make the doc changes.

There are a number of more-or-less complex factors that determine what data is available in a form:

## Both `app` and `contact` forms

Both `app` and `contact` forms can access the current user's contact data at `inputs/user`.  The data provided is simply what is available on the user's contact doc (plus an additional `language` field that contains the user's currently selected language code).

## `contact` forms

Forms for adding contacts have access to a few fields that can be accessed _either_ at the top level _or_ as children of the `inputs` group.  These fields are contained in a group that is named for the type id of the contact being added (so `person`, `clinic`, etc).  

- (type id - `person`/`clinic`/etc)
  - `parent` contains the doc id for the new contact's parent contact doc.  Also, `person/type` will always contain
  - `type` always seems to be set to "contact"
  - `contact_type` - the type of the contact being added (should match the group name, I think...)

So, when adding a new person, you can access the id of the parent contact at either `inputs/person/parent` or `person/parent` (but you should not reference both places in the same form).  

## `app` forms

Reports can be added in several ways.

### Adding from "Reports" tab

When adding from the "Reports" tab, no additional data is available to the form beyond the user data mentioned above.

(It seems there will be no value for `source`???)

### Adding from "People" tab

When adding from the "People" tab, the `app` form has access to a considerable amount of data for the contact in context.  Once again, all of this data will be accessible in the form either at the top level or within the `inputs` group.

- `source` will be "contact" when adding from the "People" tab
- `contact` group containing all the fields from the doc of the contact in context 
  - (Note it appears that in some situations, certain other documents referenced by the contact in context are hydrated and included here too, but I am not exactly sure what the criteria is for that....)

#### `contact-summary` data

`app` forms added from the "People" tab additionally can access the `contact-summary` data associated with the contact in context. This is done by referencing an instance named "contact-summary" from the form config. E.g. `instance('contact-summary')/context/my_field`, where `my_field` is a field set on the contact-summery.  See [this documentation](https://docs.communityhealthtoolkit.org/apps/reference/contact-page/#care-guides) for more information.

### Adding from task

`app` forms created via a task have access to any data in the `inputs` group that was [supplied by the task](https://docs.communityhealthtoolkit.org/apps/guides/tasks/pass-data-to-form/).  Also, in this case the `source` field (at the top level or `inputs/source`) will be "task".

**Comment by kennsippell** [comment]
i suspect It would be useful to include a full list of all channels which can be used to get data into forms, then a summary of  what channels are available in what types of forms, and finally clear documentation on how to use each channel

1. data from CHT passed via inputs
2. data from tasks passed via inputs
3. "looking up" data based on document id with db-object
4. data from contact-summary via instance()
5. reserved keywords in contact forms

1 i believe there is different data available to app forms and to contact forms
1 need to be clear what data is hydrated and what isn't
2 and 4 is only available in app forms
3 has the potential to overwrite other useful information if not done carefully
5 is available only in contact forms

**Comment by jkuester** [comment]
> 5. reserved keywords in contact forms

@kennsippell do you mean the special groups named for the contact_type (e.g. `person`/`clinic`/etc) or are you talking about something else?

**Comment by kennsippell** [comment]
I think there are some reserved keywords in contact forms like `PARENT`. I'm not sure of the full list. 
https://github.com/medic/cht-core/blob/enketo-service-refactor/webapp/src/js/enketo/contact-saver.js#L34

**Comment by jkuester** [comment]
![image](https://user-images.githubusercontent.com/8441903/171678174-156d2a82-5b8a-469a-979c-547ad4c5738e.png)

Example of saving `user` data as metadata on the form.
