### ISSUE TITLE
Clarify CHT vs CHT-Core in our architecture documentation

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-docs#309]
Page: /core/overview/architecture/
Version: 2020-07-06 11:44:06 -0700 -0700
---

On the [architecture](https://docs.communityhealthtoolkit.org/core/overview/architecture/) page, we should consider changing the label that says "CHT" to be "CHT-Core".  CHT is supposed to be the platform, which includes other components (such as RapidPro).

**Comment by garethbowen** [comment]
@n-orlowski Do you have the editable version of this image? Could you share it with me or make this change?

**Comment by n-orlowski** [comment]
@garethbowen  Updated via https://github.com/medic/cht-docs/pull/310 (+[editable version](https://docs.google.com/presentation/d/1j4jPsi-gHbiaLBfgYOyru1g_YV98PkBrx2zs7bwhoEQ/edit#slide=id.p))
