### ISSUE TITLE
PDF file locations

### ISSUE THREAD

**Issue by ronna** [medic/cht-docs#323]
I am working on https://github.com/medic/cht-core/issues/6489 and I can not locate where pdf files are stored in CHT docs repository. I would like to link to the following files:

https://github.com/medic/cht-core/blob/87d6db9c51e1b2f12d5b34e20497f94a165eb12c/release-notes/docs/3.8.0.md
line 29

https://github.com/medic/cht-core/blob/8322907698ab8ccbb9b930330dc074ab268e45cb/release-notes/docs/3.2.0.md
line 18

https://github.com/medic/cht-core/blob/dfeee0069d8f026af249b42ce7fabbdc1bfcd8b8/release-notes/docs/3.4.0.md
line 44

**Comment by MaxDiz** [comment]
Hi @ronna thanks for picking this issue up! The .pdf files can be re-pointed to the following doc site resources:

> https://github.com/medic/cht-core/blob/8322907698ab8ccbb9b930330dc074ab268e45cb/release-notes/docs/3.2.0.md
line 18

https://docs.communityhealthtoolkit.org/apps/reference/app-settings/transitions/#muting

> https://github.com/medic/cht-core/blob/dfeee0069d8f026af249b42ce7fabbdc1bfcd8b8/release-notes/docs/3.4.0.md
line 44

https://docs.communityhealthtoolkit.org/apps/reference/resources/#branding

> https://github.com/medic/cht-core/blob/87d6db9c51e1b2f12d5b34e20497f94a165eb12c/release-notes/docs/3.8.0.md
line 29

I don't see the pdf in the line that you referenced

**Comment by ronna** [comment]
Hi @MaxDiz 

Thanks for the pointers. I have updated my cht-core pull request

**Comment by MaxDiz** [comment]
great! Is this issue ok to close?

**Comment by ronna** [comment]
sure, please go ahead and close the issue. Thanks for your support
