### ISSUE TITLE
Consider adding GUI tools to docker instructions

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#365]
Recently had an orphaned sub title for " Use Kitematic (GUI for Docker tools)" on the [Docker page](https://docs.communityhealthtoolkit.org/core/guides/docker-setup/). Since there was no content for this subtitle, we removed it.

However, maybe we want to add information about using a GUI to manage docker? This might be helpful for those less comfortable with both Docker and the command line. Here's a link for [Kitematic](https://kitematic.com/).

**Comment by jkuester** [comment]
@mrjones-plip, now that Docker Desktop is available for all platforms (and is our [recommended approach](https://github.com/medic/cht-docs/pull/1531)) do you think we can close this issue?

**Comment by mrjones-plip** [comment]
ah - yeah - good call!
