### ISSUE TITLE
add step to install pyxform when installing medic-conf

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#370]
on our `medic-conf` [repo](https://github.com/medic/medic-conf), there's a key step that's listed when installing: install pyxform.  This step is not on [the docs page where you set up your local environment](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/).  We should add it to step 1 there.  As well, we should link to the `medic-conf` repo so that folks can read more about how to install it for things like windows and also learn more about it's uses.

**Comment by garethbowen** [comment]
@mrjones-plip This has been merged - can it be closed?

**Comment by mrjones-plip** [comment]
yes, thanks for the reminder @garethbowen !
