### ISSUE TITLE
Improve 'DHIS2'

### ISSUE THREAD

**Issue by shreyakb** [medic/cht-docs#372]
Could we remove the spellcheck error on "CHW's" for a cleaner visual? Thanks!

![image](https://user-images.githubusercontent.com/7915295/98665300-81269c80-2371-11eb-88af-b70d18445119.png)

Page: /apps/features/integrations/dhis2/
Version: 2020-07-30 21:39:29 -0700 -0700
---

**Comment by garethbowen** [comment]
@abbyad You added this image - do you still have the source version or know who authored it? Otherwise we could photoshop it a little.

**Comment by abbyad** [comment]
I had taken this from another doc and didn't have the source image, but clipped out the swiggly line.

**Comment by garethbowen** [comment]
Perfect, thanks!
