### ISSUE TITLE
Missing documentation for UHC feature

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-docs#400]
Trying to understand the UHC feature while investigating a bug in home visit counts from Muso. This feature doesn't appear to be documented.

[here](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/#app_settingsjson) there is some documentation for three uhc variables in app_settings. Otherwise, this feature doesn't appear in the documentation.

There is no reference to how app builders should actually use and control this feature:

* fields.visited_contact_uuid
* fields.visited_date

https://github.com/medic/cht-core/blob/master/ddocs/medic-db/medic-client/views/visits_by_date/map.js

**Comment by kennsippell** [comment]
https://github.com/medic/cht-core/blob/85804e8d6fad7133684aabd46ad0a9566b11b23e/release-notes/docs/2.16.0.md#view-date-last-visited-for-places-on-the-people-tab

**Comment by joyannee** [comment]
Draft [UHC documentation](https://docs.google.com/document/d/1RKeMGET_ZlozRt1Wr2gD9HO8vNDLxnquy_lrbhArd24/edit)- cc @michaelkohn
