### ISSUE TITLE
tabular schedule render issues 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#424]
@maremegaye  and I were testing out the new [tabular schedules](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#tabular-schedules) feature in her [MNCH docs branch](https://github.com/medic/cht-docs/pull/422).  We found that the table:
* does not always wrap the headers, so some are one line, others are on two (they should all be the same, preferably 2 lines)
* does not show the emoji for all browsers

For @maremegaye, her Safari and Chrome doesn't wrap.  I'm able to reproduce the same no wrap issue and also emoji do not show up on my older MacOS version running High Sierra 10.13.6 (build 17G14042 from November 2020). Line wrap works correctly in FireFox, but emoji is still broken.

Here's screenshots of the [docs style guide URL](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#tabular-schedules).  Note all versions include browser version in them (should be latest of everything as of now)

Firefox:

[<img src="https://user-images.githubusercontent.com/8253488/106798195-831b9700-6612-11eb-9a27-d81f1f2a1299.png" width=40% height=40%>](https://user-images.githubusercontent.com/8253488/106798195-831b9700-6612-11eb-9a27-d81f1f2a1299.png)

Chrome:

[<img src="https://user-images.githubusercontent.com/8253488/106798213-8a42a500-6612-11eb-8981-a1e9432c37a5.png" width=40% height=40%>](https://user-images.githubusercontent.com/8253488/106798213-8a42a500-6612-11eb-8981-a1e9432c37a5.png)

Safari:

[<img src="https://user-images.githubusercontent.com/8253488/106798226-8f075900-6612-11eb-9de7-b24921d2ae1a.png" width=40% height=40%>](https://user-images.githubusercontent.com/8253488/106798226-8f075900-6612-11eb-9de7-b24921d2ae1a.png)

FYI @abbyad

**Comment by abbyad** [comment]
Nice testing! The wrapping seems to be width dependent, and tricky to always get it right because it could be affected by device/browser/font/zoom. Perhaps we should consider doing the title headers differently now that we have a shortcode (and more control/power!). Similarly, we could use the shortcode to manage images instead of emoji. We can probably come up with a notation to make it as easy as possible for the page editor.

**Comment by mrjones-plip** [comment]
It looks like there's a systemic problem - On Ubuntu 18.04 in Chromium based browsers -  Chrome, Chromium and Brave all fail both emoji rendering and line wrap.  Here's Brave, Chromium and Chrome top to bottom on [the same URL](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#tabular-schedules):

[<img src="https://user-images.githubusercontent.com/8253488/106812493-9e8f9d80-6624-11eb-9126-9535578f0317.png" width=40% height=40%>](https://user-images.githubusercontent.com/8253488/106812493-9e8f9d80-6624-11eb-9126-9535578f0317.png)

**Comment by mrjones-plip** [comment]
OK, the width was easy.  We have this selector:

```css
.schedule + table td {
  width: 3em ;
}
```

and we don't want to target table data (`td`), but instead table header (`th`).  The tables all work once I change it to:

```css
.schedule + table th  {
  width: 3em ;
}
```

I'll pull together a PR now. 

 As well, speaking of selectors, I think we might get off easy either with the the [`:empty` psuedo-class](https://developer.mozilla.org/en-us/docs/Web/CSS/:empty) or the [`empty-cells` property](https://developer.mozilla.org/en-US/docs/Web/CSS/empty-cells) to fix the emoji issue.  Turns out the [green circle](https://emojis.wiki/green-circle/) emoji isn't the most friendly one (oddly [blue works](https://emojis.wiki/blue-circle/) a lot better in my testing?!). 

I suggest we avoid emoji all-together and come up with a solution that's easy for editors and Just Works™.

**Comment by mrjones-plip** [comment]
what WHAT!?! double negative, quadruple psuedo class in this here house:

```css
.schedule + table td:not(:first-child):not(:empty)  {
  vertical-align: middle;
  background-image: url("/circle.svg");
  background-repeat: no-repeat;
  background-position: center;
  text-align: center;
  color: #78b159;
  font-size: 1pt;
}
```
