### ISSUE TITLE
Lacking info on configuring the "conditional_alerts

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#426]
Page: /apps/reference/app-settings/transitions/
Version: 2020-08-21 13:32:42  0300  0300
---

The `conditional_alerts` are configured with the `app_settings.alerts` field, but that isn't documented well.

**Comment by garethbowen** [comment]
@abbyad Dupe of #427 ?

**Comment by abbyad** [comment]
Ya, and weird! It looks like the second `"` threw GitHub off and they created two issues 🤔
