### ISSUE TITLE
Improve 'Generic'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#429]
Page: /apps/features/integrations/generic/
Version: 2020-12-16 14:39:28  0100  0100
---

The term "generic integration" makes sense from the CHT side, but from an implementer or app developer perspective it would be more clearly understood as "custom" integration. After a quick internal poll there was wide representation of roles in the 6 assents, and no dissents.

**Comment by michaelkohn** [comment]
Should this be closed?
