### ISSUE TITLE
Add more details to tasks tutorial

### ISSUE THREAD

**Issue by smbuthia** [medic/cht-docs#471]
The [tasks tutorial](https://docs.communityhealthtoolkit.org/apps/tutorials/tasks/) has some gaps that need to be filled for the benefit of CHT beginners. 

For example, there's no mention of which file someone will be working from or where one can add extra functions.

Revise this tutorial to eliminate the need to make assumptions or dig elsewhere for information.

**Comment by derickl** [comment]
Closed by https://github.com/medic/cht-docs/pull/564
