### ISSUE TITLE
CHT APP not accessible via the mobile phone option and remotely using the local dns

### ISSUE THREAD

**Issue by andrineM** [medic/cht-docs#482]
We have a scenario where the setup and configuration of both pihole and CHT worked ok and we could access the app via the browser on the host server (Where the application is installed). However, any remote access via https://cht.my.local-ip.co did not work including the mobile phone app option.

**Comment by andrineM** [comment]
@nomulex @Hareet @henokgetachew @derickl  Requesting your assistance on this issue.

**Comment by derickl** [comment]
@mrjones-plip any tips?

Do you have a DNS server on your network that resolves `cht.my.local-ip.co ` to an actual host within your network?

@andrineM  could you experiment with  [this](https://nip.io/) and evaluate if running a self-hosted version would  be of value to you?

**Comment by mrjones-plip** [comment]
@andrineM  - Thanks so much for opening this issue!  

Given there seems to be [on going issues](https://github.com/medic/cht-core/issues/6884) you're facing and that this is the repository for tracking issues with the CHT docs site, I'm going to close this ticket and gather all the updates  in the [current forum thread](https://forum.communityhealthtoolkit.org/t/prototyping-a-fully-offline-cht-server-environment/1232/2).
