### ISSUE TITLE
Add technical roadmap

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#490]
The technical roadmap should be included on the docs site. A good place would be a new _Technical Roadmap_ page in [Overview of CHT Components](https://docs.communityhealthtoolkit.org/core/overview/). 

The roadmap can be included on the page with this embed code:
```
<iframe src="https://portal.productboard.com/pqvfjf8prkx3uvxt8fu3iejs" frameborder="0"></iframe>
```

**Comment by garethbowen** [comment]
Can we give the Technical Roadmap a subdomain just like the Product Roadmap has now, ie: https://roadmap.communityhealthtoolkit.org/ ?

**Comment by abbyad** [comment]
We definitely can. It requires some infrastructure work, as we did in this other [issue](https://github.com/medic/medic-infrastructure/issues/230) (private link). If you create a similar issue I believe either of us can take care of the Productboard side while the infra side gets handled.

**Comment by garethbowen** [comment]
[Issue raised](https://github.com/medic/medic-infrastructure/issues/305)
