### ISSUE TITLE
Improve 'Africa’s Talking SMS Aggregator'

### ISSUE THREAD

**Issue by shreyakb** [medic/cht-docs#494]
Page: /apps/guides/messaging/africas-talking/
Version: 2021-04-09 06:59:14  0300  0300
---

Flagging that we need to update Medic branding in the image (remove "Mobile"). Thanks!

![image](https://user-images.githubusercontent.com/7915295/118085876-bb383000-b3e0-11eb-9ee9-1f0ddd649ee9.png)

**Comment by garethbowen** [comment]
@abbyad You were the last one to touch this image. Do you have the source?

**Comment by abbyad** [comment]
Thanks for highlighting @shreyakb! 

I converted this page to markdown but wasn't involved in the creation of the original. I think I found the [original](https://docs.google.com/presentation/d/1vW3lVD5cfBJd-wn5KTah1zGJ1La9n96URsNjxLHjEjM) in drive though.

**Comment by abbyad** [comment]
The gateway section needed a fair bit of reorganization now that we have multiple gateways. As part of that reorganization the image was not as relevant, escpecially given that it was not technically accurate as it was. If someone feels as though conceptual images would help please open a new issue.
