### ISSUE TITLE
Improve use of footnotes

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#509]
Page: /apps/reference/app-settings/transitions/
Version: 2021-03-24 06:41:04  0200  0200
---

The footnotes are a relic from a previous document format, and are difficult to find/follow in the doc site:

![image](https://user-images.githubusercontent.com/789512/120338943-adc8e400-c2c2-11eb-9b61-e7a4f051432e.png)

When reading the documentation it isn't clear where to go to see the footnotes since they aren't cross-linked, and [7] is also separated out to the next header.

We don't use footnotes elsewhere in the doc site, so we should re-evaluate if footnotes are the best way to include this information, and if so (1) restructure the footnotes to make the content clearer, as well as (2) add best practices about them in the style guide.

**Comment by esthermmoturi** [comment]
Closed by https://github.com/medic/cht-docs/pull/1714
