### ISSUE TITLE
Add detail on the folder structure for multimedia upload from cht-conf

### ISSUE THREAD

**Issue by newtewt** [medic/cht-docs#534]
The current docs mention the folder for multimedia but there doesn't seem to be any detail on the full structure needed to upload images. 

[Media files in the {form_name}-media directory (optional)](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/)

The full structure is   `{form_name}-media/images/image.png`

**Comment by garethbowen** [comment]
@newtewt As far as I can tell the `images` subdirectory is only needed if the xform specifies `images/...`, for example, `<value form="image">jr://image.jpg</value>` should work if the attachment is in `{form_name}-media/image.jpg`. I agree this could be more clear in the documentation, but I wanted to make sure we're on the same page before making the change. Does this match your understanding?

**Comment by newtewt** [comment]
hmm I thought the images directory was required. I just tested it now and it's working using our demo multimedia form and the image.jpg being in `multimedia-media/image.jpg`

**Comment by garethbowen** [comment]
Merged.
