### ISSUE TITLE
Fix two chars in Local Setup, add entry to .gitignore

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#589]
On the [Local Setup page for uploading data](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/#3-upload-test-data) we have an extra "`." after the command:

```
cht --url=https://medic:password@localhost --accept-self-signed-certs csv-to-docs upload-docs`.
```

As well, it looks like new versions of `hugo` have a `.hugo_build.lock` file that we should be sure to exclude from git. I'm on `v0.91.0-D1DC0E9A+extended` which is very latest and am getting asked to commit this file.

**Comment by tmatheas** [comment]
@mrjones-plip If this issue is fixed, please close the issue.

**Comment by mrjones-plip** [comment]
ah - thanks for the reminder @tmatheas !
