### ISSUE TITLE
Move 'Supported Versions' content

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#600]
Now that we have a high [level _Releases_ page](https://docs.communityhealthtoolkit.org/core/releases/) with _Release Notes_, ([eg 3.13.0](https://docs.communityhealthtoolkit.org/core/releases/3.13.0/)) it seems as though [the _Supported Versions_ page](https://docs.communityhealthtoolkit.org/core/overview/supported-software/) is in the wrong place and unnecessary. I propose we move the content of the Supported Versions page to the [Releases page](https://docs.communityhealthtoolkit.org/core/releases/) so that it is seen and maintained together.

Note that we should also create and test the alias when removing the current page.

**Comment by mrjones-plip** [comment]
@abbyad - sorry! I was adding in some links to the body text and see I deleted your header with path and edit date (you have it on #67). I can't quite recreate which it is, but hopefully my inline links make up for it :pray:

**Comment by abbyad** [comment]
Ah, no worries. I can access the edited versions still, so could restore the path and edit date but it doesn't seem useful enough to restore at this point.
