### ISSUE TITLE
"Edit this page" links are broken

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#619]
With change of `master` to `main` the "edit this page" links are broken:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/789512/151597758-91c4aad7-8676-4b24-8a0e-4886cd0ee9da.png">

**Comment by abbyad** [comment]
This looks like it would be resolved by https://github.com/medic/cht-docs/pull/617, so assigning to @jonathanvq

**Comment by mrjones-plip** [comment]
Fixed in #629
