### ISSUE TITLE
Create self-hosting tutorial

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#64]
Self-hosting has recently increased in importance for our partners to meet data management guidelines. Instead of answering each partner request separately, it would be helpful to create a comprehensive tutorial to point partners to when they ask for assistance.  

Existing resources on the doc site to review/consolidate: https://docs.communityhealthtoolkit.org/apps/guides/hosting/

**Comment by MaxDiz** [comment]
Adding to 3.10 since there seems to some momentum on the topic. It is not a blocker to the release.

**Comment by garethbowen** [comment]
Added to site reliability support dashboard for any SRE to pick up.

**Comment by mrjones-plip** [comment]
Heya! During automated testing for 404 links in the docs site, it was discovered that on our [hosting guide](https://docs.communityhealthtoolkit.org/apps/guides/hosting/ec2-setup-guide/), we have a link to "Prepare Self-Hosting System" that goes to: https://github.com/medic/medic-infrastructure/tree/master/self-hosting/prepare-system. This link is 404 because you need to be logged in to view it.  It'd be great if in this ticket we could make the `medic-infrastructure` GH repo open to the public!

**Comment by garethbowen** [comment]
We probably can't make the whole GH repo public, but we should separate infrastructure info that's public (particularly self-hosting info), from infrastructure info that is private or only relevant to Medic teammates.

**Comment by mrjones-plip** [comment]
> We probably can't make the whole GH repo public, but we should separate infrastructure info that's public (particularly self-hosting info), from infrastructure info that is private or only relevant to Medic teammates.

Ah - thanks for your guidance. I'm not sure what's sensitive or not, so much appreciated.

**Comment by MaxDiz** [comment]
related #196

**Comment by garethbowen** [comment]
This is covered by the SRE support dashboard so I'm removing it from the product release.

**Comment by MaxDiz** [comment]
Pulling in comment from @newtewt from the forum:

> Section 2 of [ec2 setup](https://docs.communityhealthtoolkit.org/apps/guides/hosting/ec2-setup-guide/#2-create-or-restore-ebs-volume) refers to mounting the EBS volume. The statement about ‘Follow the instructions here: Using EBS Volumes’ has details about using mkfs to assign a file system of xfs and then we specify how to do it in the next step using ext4. We should probably clarify which is needed.

**Comment by newtewt** [comment]
Might want to add for self hosting that we know which versions are good to use. EX: Ubuntu 18.04, python2, etc...

**Comment by nomulex** [comment]
The initial [PR](https://github.com/medic/cht-infrastructure/pull/6) is here. Please review and revert.

**Comment by MaxDiz** [comment]
Hi @nomulex does this tutorial supersede [this documentation resource](https://docs.communityhealthtoolkit.org/apps/guides/hosting/self-hosting/)? It would be great to have the most up to date version on the doc site. @smbuthia can also help with reviewing to add as a doc site tutorial.

**Comment by nomulex** [comment]
Hi @MaxDiz , yes . This Supersedes that resource. It is concise and chronological  as expected when setting up self hosting.

**Comment by mrjones-plip** [comment]
I some how missed that the PR is to update that [the readme.md]( https://github.com/medic/cht-infrastructure/pull/6) for the `cht-infrastructure` repo and not to update the page @MaxDiz [cited](https://docs.communityhealthtoolkit.org/apps/guides/hosting/self-hosting/). Maybe let's get this doc live as an MVP (MVP of documentation? Sure, why not ;) and then immediately port it to the docs site?  What we should avoid is having the same information twice - we'll for sure forget to update one when we update the other and they'll become divergent.

**Comment by nomulex** [comment]
I agree with @mrjones-plip , We can move this to one place. I think @smbuthia is working on that.
