### ISSUE TITLE
Redo install instructions for happy path copy paste

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#700]
Right now, the [CHT Core developer install docs](https://github.com/medic/cht-core/blob/575bc95a8ccf82b211a13fec9d3228f71169405f/DEVELOPMENT.md) are intimidating and error prone to new comers.  We should redo them to be "copy paste-able".  This way, assuming a happy path, a new developer can just blindly copy paste away and end up with a functional dev environment.

Presumably we'll need three sets of instructions: mac, linux and windows.  Possibly two with mac/linux and windows?

[This gist](https://gist.github.com/mrjones-plip/7bbe7b0a44ce7876a551b9730c6fc43d) has the start of what we should use for the linux base.

**Comment by mrjones-plip** [comment]
@craig-landry  & @garethbowen  - I have a [nice first draft on the gist](https://gist.github.com/mrjones-plip/7bbe7b0a44ce7876a551b9730c6fc43d) \o/  Early feedback welcome.

Question - I feel like a true developer environment allows for offline users and android devices.  I think we should add a line to fire up [nginx-local-ip.](https://github.com/medic/nginx-local-ip/)  Thoughts? Concerns?

**Comment by craig-landry** [comment]
Would you please change the format to a commit & PR to the [DEVELOPMENT.md](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md) file? That will allow for easier feedback. To your point of "first draft", you can do it as a Draft PR too if you'd like :)

**Comment by craig-landry** [comment]
To the question of [nginx-local-ip](https://github.com/medic/nginx-local-ip/), I think it's a good thing to include. For the purpose of getting useful incremental progress I would like to get this basic setup done and merged and then we can work out instructions for putting it all together with Android and  nginx-local-ip.

**Comment by craig-landry** [comment]
A more general comment on the approach is that I'm hoping we can get it feeling a lot closer to the format seen on this [Docker install page](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04).

**Comment by garethbowen** [comment]
> a lot closer to the format seen on this Docker install page

Yes, that's perfect IMO. A good balance of human readable and copyable.

> Presumably we'll need three sets of instructions: mac, linux and windows. Possibly two with mac/linux and windows?

I think we'll need 3 but I dislike the idea of having to maintain 3 separate docs. If they only differ a little we may get away with inlining them (linux and mac in particular). Otherwise I don't see any other option with markdown.

> I think we should add a line to fire up [nginx-local-ip.](https://github.com/medic/nginx-local-ip/) Thoughts? Concerns?

Good call.

Another idea - would it be better to do this to the `archv3` branch? The instructions will change a bit with the launch of 4.0.0 and the timing may well work out so we don't need to duplicate effort here.
