### ISSUE TITLE
Improve 'Securing Android Devices'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#716]
Page: /apps/guides/security/securing-android/
Version: 2020-06-05 21:05:09 -0400 -0400
---

Revisiting this page after a [recent forum conversation](https://forum.communityhealthtoolkit.org/t/enhancing-security-of-cht-apps-through-two-factor-authentication-2fa/1953?u=marc), the MDM section felt a bit bare and outdated. Creating this issue to connect an upcoming PR.

**Comment by garethbowen** [comment]
Merged.
