### ISSUE TITLE
Improve '.permissions'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#718]
Page: /apps/reference/app-settings/user-permissions/
Version: 2022-05-03 05:13:19  0300  0300
---

From @craig-landry:
> There was some confusion on a project with the `can_edit` permission since users can still create reports on devices, but they just don't sync. That is a risk since it means reports are getting created and never synced and may result in data loss.

**Comment by abbyad** [comment]
Although the docs could be improved, it seems as though it would help to resolve what looks like the [underlying defect](https://github.com/medic/cht-core/issues/6215), that the permission controls the sync only and doesn't prevent the user from taking the edit action within the app.

**Comment by garethbowen** [comment]
I propose we fix the underlying defect, and also this related issue https://github.com/medic/cht-core/issues/6505 and update the docs as part of that issue.

**Comment by abbyad** [comment]
Great, let's do that. I'll let you schedule those issues as needed. It will be some time before any changes make it to all deployments, so I'll open a PR with small note in the docs in the meantime.

**Comment by garethbowen** [comment]
Merged.
