### ISSUE TITLE
create reusable section layouts for the documentation site

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#76]
The revised documentation site index (#194) contains a number of sections that generally follow the same information sequence. The layout of the documentation site sections can have a big influence on how they're read, and what visual impact the content has. To create uniformity and make for easier user comprehension, it would be helpful to maintain a consistent layout when navigating between sections. We should create layout templates for:

- feature tours
- reference apps
- others?

**Comment by abbyad** [comment]
@MaxDiz can we close this now that we have pages in a pretty consistent format?
