### ISSUE TITLE
Look into multilingual support for documentation site

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#77]
Many of our project deployments are in locations where english is not the primary language. To improve relevancy of the documentation site for this audience, having a fully translated version available would be helpful. This issue is to detail exploration of multilingual translation support options. Even better if a single solution can be applied to other resources where product information is communicated - [CHT forum](https://forum.communityhealthtoolkit.org/), [blog](https://medicmobile.org/blog), and similar.

cc: @Fatoufall @maremegaye

**Comment by abbyad** [comment]
Hugo, which we are now using for generating the doc site has multi-lingual support. Can we close this issue now, and revisit if/when we want to translate certain sections?

**Comment by MaxDiz** [comment]
Hugo sounds like a good native option. 
I'd like to have a concrete decision on approach before closing the issue. We can delay until there is a clear partner need.

**Comment by abbyad** [comment]
I think our approach is to use Hugo pages for translations when we need it. I don't think there is anything more to decide on right now since we are not considering translating the entire documentation site at this time.

**Comment by MaxDiz** [comment]
ok by me
