### ISSUE TITLE
Improve 'How to bulk load users'

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-docs#780]
Page: /apps/guides/data/users-bulk-load/
Version: 2022-08-17 17:49:02 -0700 -0700
---

As [reported by a user in the CHT forum](https://forum.communityhealthtoolkit.org/t/bulk-user-upload-chws-and-supervisors/2161), these [instructions](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/#importing-users) we provide to create copies of the sheet seem to be insufficient:
> 2. Copy the “contact.chw” and “contact.chw_VLOOKUP” worksheets so that you have a set of the pair per level of your hierarchy. If your hierarchy was “Central -> Supervisor -> CHW”, you would have 3 pairs (6 worksheets total). Be sure each worksheet is named accurately.

Please consider adding more details such as modifying the data validation and other fields for another level in the hierarchy.

**Comment by esthermmoturi** [comment]
Fixed by https://github.com/medic/cht-docs/pull/1115
