### ISSUE TITLE
Broken link in 'app_settings.json'

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-docs#793]
Page: /apps/reference/app-settings/
Version: 2022-05-03 07:56:17  0545  0545
---

In [this section](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/#sample-usage), the link to `pupil` package is broken:
https://www.npmjs.com/package/pupil#rule-strings

I couldn't find the working link.

**Comment by garethbowen** [comment]
Merged.
