### ISSUE TITLE
Improve 'Interoperability'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#813]
Page: /apps/concepts/interoperability/
Version: 2022-09-23 10:04:29  1200  1200
---

The page accidentally uses "Moderators", should be "Mediators".

http://openhim.org/docs/user-guide/mediators/
https://wiki.ohie.org/display/SUB/Design+of+the+Interoperability+Layer+core+using+Node.js

**Comment by garethbowen** [comment]
Merged.
