### ISSUE TITLE
Add "Muting" as a feature to 'Contacts'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#816]
Page: /apps/features/contacts/
Version: 2022-09-15 09:07:15  0700  0700
---

The "muting" of contacts is mentioned in the documentation, but not explained as a feature.

A feature overview was mentioned in the [3.2 release notes](https://docs.communityhealthtoolkit.org/core/releases/3.2.0/#muting), but is a broken link (at the time this issue was opened). The [original pdf](https://github.com/medic/medic-docs/blob/3afbfca835a2836b2ce27f589f2613ccc368b2fc/features/muting-overview.pdf) was [updated](https://github.com/medic/medic-docs/blob/91badc2a347f86fd2b42b1c9ab9527b5982ee9c0/Muting%20Features%20Overview.pdf) and is now archived with medic-docs. We can take useful parts from that doc to highlight the muting feature on the docs site.

**Comment by esthermmoturi** [comment]
This was added [here](https://docs.communityhealthtoolkit.org/building/workflows/muting/).
