### ISSUE TITLE
Document 4.x self hosting

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-docs#831]
How do we recommend self hosters run 4.x today.

Needs to cover:

- single, multi, and distributed couchdb nodes.
- backups
- logs
- etc

**Comment by henokgetachew** [comment]
PRs submitted.

**Comment by mrjones-plip** [comment]
Docs are live!
* https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting-multiple-nodes/
* https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting-single-node/
* https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/adding-tls-certificates/

**Comment by mrjones-plip** [comment]
we didn't hit this, so reopening:
backups
logs

**Comment by mrjones-plip** [comment]
with logs and backups added, closing this ticket out:
* https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/logs/
* https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/backups/
