### ISSUE TITLE
Document 4.x CHT Core Developer Setup

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-docs#837]
The [CHT Core Developer Setup page](https://docs.communityhealthtoolkit.org/apps/guides/hosting/core-developer/) is out of date for 4.x.

For example, the `secure-couchdb` setup is not needed anymore in 4.x.

**Comment by andrablaj** [comment]
@garethbowen @mrjones-plip I am happy to start updating the documentation for the developer setup, and this is what I intend to do:

- Move the existing page under `hosting/3.x` and create a new one under `hosting/4.x`, with updated setup steps.
- Reach out to @dianabarsan to validate the links/content of the `docker-compose` file.

I would like to have this ready when Samuel starts, so he can setup his development environment for 4.x.

Any thoughts/concerns, or should I move forward?

**Comment by garethbowen** [comment]
@andrablaj Yes that sounds fine. The other alternative is just to add text for "if setting up CHT 3.x...". I think that'd be my preference until the two setups differ significantly, but I'll leave it up to you to make a call!
