### ISSUE TITLE
Bulk User Upload: differences between different upload types and require fields for each

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#846]
The [current docs](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/) for bulk user upload only cover when you want to create all three of users, contacts and places.  It can be confusing for CHT admins who only want to create users and contacts, re-using existing places. 

We should improve the docs around this. This might include:
* ~~adding more sample spreadsheets~~
* ~~adding lists of column names and their purpose~~
* document [more troubleshooting](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/#trouble-shooting) when adding different types of places based on custom configs

**Comment by esthermmoturi** [comment]
Hey @m5r , was this done?

**Comment by m5r** [comment]
@esthermmoturi no it wasn't done but I will open a PR this week to document adding place types

**Comment by esthermmoturi** [comment]
Thanks @m5r , I look forward to the PR.

**Comment by esthermmoturi** [comment]
Fixed by https://github.com/medic/cht-docs/pull/1540
