### ISSUE TITLE
Create documentation describing the different CouchDB databases and what is in each

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-docs#85]
There are a number of different databases in CouchDB, but I can't find any documentation anywhere that gives an overview of what each one is, how they get named, what you can find in them, etc...

I would expect that documentation to be [here](https://github.com/medic/medic-docs/blob/master/development/db-schema.md).

In addition, for each different section, [Reports](https://github.com/medic/medic-docs/blob/master/development/db-schema.md#reports) for example, we should specify which database that document type can be found in.

<img width="1217" alt="Screen Shot 2020-02-13 at 1 12 21 PM" src="https://user-images.githubusercontent.com/10096985/74411509-83e87580-4e63-11ea-82d7-c08c2dd9cc0c.png">

**Comment by esthermmoturi** [comment]
This has been fixed by the above mentioned PRs. Documentation can be found [here](https://docs.communityhealthtoolkit.org/building/guides/database/)
