### ISSUE TITLE
Add documentation that covers target aggregates

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-docs#860]
I couldn't find relevant documentation that explains how target aggregates work and how they can be enabled in the docs site. 
I did find a closed issue that [covers that](https://github.com/medic/cht-docs/issues/3), which also links to a nice presentation about target aggregates. 

A request for documentation [came through the forum](https://forum.communityhealthtoolkit.org/t/targets-summarized-by-village-for-a-user-in-a-upper-level-in-the-hierarchy/2274)

**Comment by esthermmoturi** [comment]
I think this is covered [here](https://docs.communityhealthtoolkit.org/building/features/supervision/#chw-aggregate-targets) and [here](https://docs.communityhealthtoolkit.org/building/targets/targets-js/) .

**Comment by dianabarsan** [comment]
Awesome!
