### ISSUE TITLE
4.0 local setup instructs to store upgrader and cht compose files in the same folder

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-docs#873]
https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/#1-create-docker-compose-files

The upgrader docker-compose file should be stored separately than the CHT docker-compose files, otherwise the upgrader will be unable to start the CHT.

**Comment by mrjones-plip** [comment]
@dianabarsan  - thanks for filing this! 

Right now the docs have folks keep the two core and couch compose files in `~/cht-local-setup/data/` and then the upgrade compose file in `~/cht-local-setup/`.  It was my understanding this was sufficient separation.  Should we change it so we store the upgrade in `~/cht-local-setup/upgrade`?

Here's the code from the docs for easy reference:

> `curl -s -o ./data/cht-4-core.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3Amaster/docker-compose%2Fcht-core.yml`
> `curl -s -o ./data/cht-4-couch.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3Amaster/docker-compose%2Fcht-couchdb.yml`
> `curl -s -o cht-upgrader.yml https://raw.githubusercontent.com/medic/cht-upgrade-service/main/docker-compose.yml`

**Comment by dianabarsan** [comment]
Oh, I see! I missed the separation that existed, but I think your suggestion of further separating them is the best idea. 
I think we should go even further and put couch data in a separate folder, and not have people confused by 

```
.IsADirectoryError: [Errno 21] Is a directory: '/docker-compose/couch'
```
(this warning is logged when the couchdb data files are in the same folder as the cht docker-compose files). 

https://forum.communityhealthtoolkit.org/t/trouble-with-adding-app-forms/744/24

**Comment by mrjones-plip** [comment]
Ah - super helpful - thanks for the explanation!  I'll grab this right quick then.
