### ISSUE TITLE
Broken header in index of 'Contributing Code'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#875]
Page: /contribute/code/
Version: 2022-09-19 10:29:51 -0500 -0500
---

The _Learn to build and host apps, and share your experiences_ header in the index is broken into three items, one of which is in bold:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/789512/204364501-7625201b-4ca3-4746-8d59-56ef1d2fad02.png">

The breaks in the index are likely due to the link being included in the header. We could try to fix the index, but given that the [style guide](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#link-paragraphs-not-titles) recommends links in paragraph, not header, we should move the link to a new body text.

**Comment by garethbowen** [comment]
Looks like this is merged - closing.
