### ISSUE TITLE
Document core contributor handbook

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-docs#895]
We have a range of docs for core developers for how to do certain things but they're spread out. Instead we want to put all core contributor resources in one place so that it's easy for contributors to find and other user types (app devs) don't end up in the wrong place by accident.

Resources that should be co-located:

- https://docs.communityhealthtoolkit.org/core/guides/releasing/
- https://docs.communityhealthtoolkit.org/core/guides/update-dependencies/
- https://docs.communityhealthtoolkit.org/core/guides/fixing-e2e-tests/
- https://docs.communityhealthtoolkit.org/core/guides/android/ (except for building flavours)
- https://docs.communityhealthtoolkit.org/core/guides/using-npm/
- https://docs.communityhealthtoolkit.org/core/guides/using-windows/
- https://docs.communityhealthtoolkit.org/core/guides/docker-setup/
- https://docs.communityhealthtoolkit.org/contribute/ (the whole section)

Move these to a top level section called "Contributor Handbook".

Missing documentation includes:

- Code design (a macro view of code style)
- Product quality (requirements like change management, CI, testing, etc)
- How to review code
- and probably much more...

**Comment by garethbowen** [comment]
@craig-landry Can you please review these suggestions to make sure we're on the same page before I start moving everything around?

**Comment by andrablaj** [comment]
@garethbowen thanks for sharing this ticket with me! I had a similar discussion with @craig-landry a few weeks ago around creating an engineering handbook for the Medic team (+ public, depending on the content). 

You can find below a draft for how that would look like:

### What?
The Medic Engineering Handbook contains best practices and guidelines we use in the engineering team at Medic.

### Why?

- “Public by default”.
- From [GitLab](https://about.gitlab.com/handbook/handbook-usage/#why-handbook-first): “Having a "handbook first" mentality ensures there is no duplication; the handbook is always up to date, and others are better able to contribute.”
- To keep the code quality bar high
- To value quality and precision over just "getting things done"
- To learn from other people's shared experiences and feedback
- To increase overall efficiency for engineers

### How?

- Make it accessible to the organization and public(?) (e.g. via Notion or `cht-docs`).
- Living document. Everyone should be able to contribute to the handbook. 
- Keep it simple.

### Content ideas

- Why a handbook?
- Team
   - Who we are
   - OKRs
   - Engineering Values (something like [this](https://playbook.obvious.in/the-engineering-playbook/engineering-first-principles))
   - House Rules (remote calls, communication style - [example](https://learn.gitlab.com/coursera-remote-work/effective-communicat), being respectful of others time, …)
   - About async work (see [GitLab’s guide](https://about.gitlab.com/company/culture/all-remote/asynchronous/))
   - People Management 
   - Learning
   - [Check other ideas here](https://learn.gitlab.com/coursera-remote-work/01-Jan)
- Developer Tools
   - IDE, version control 
- System Design & Architecture 
   - Guidelines (Prefer X over Y…) - [example](http://engineering-principles.onejl.uk/)
   - Refactoring
   - Design Docs
- Developer Experience
   - Pair programming
   - Onboarding
- Release Engineering 
   - Engineering Fundamentals Checklist (e.g. [this](https://microsoft.github.io/code-with-engineering-playbook/ENG-FUNDAMENTALS-CHECKLIST/))
   - Code reviews 
   - Automated testing ([example](https://microsoft.github.io/code-with-engineering-playbook/automated-testing/))
   - Continuous Integration
   - Continuous Delivery
   - …
- Documentation
   - Architectural Decision Records
- Team Conversations
   - Daily updates
   - Retros
- Appendix
   - Glossary
   - Vital Reading Material
   - Recommended Watching
   - Recommended Reading Links

### References
[GitLab Engineering](https://about.gitlab.com/handbook/engineering/)
[GitLab the Remote Playbook](https://learn.gitlab.com/coursera-remote-work/remote-playbook)
[Atlassian Engineering Playbook](https://www.atlassian.com/engineering/handbook)
[Obvious Playbook](https://playbook.obvious.in/the-engineering-playbook)
[Thoughtbot Playbook](https://thoughtbot.com/playbook)
[Google style guides](https://google.github.io/styleguide/)
[Microsoft Code-With Engineering Playbook](https://microsoft.github.io/code-with-engineering-playbook/)
[Microsoft Guide](https://learn.microsoft.com/en-us/previous-versions/msp-n-p/ee658096(v=pandp.10))
[Truss Playbook](https://playbook.truss.dev/docs)

I believe that some items (as the ones you mentioned in the description of the ticket) are addressed to the CHT core contributors, and some of them (as team conversations, for example) are addressed to Medic team. Nevertheless, they could both live under the same documentation, "GitLab" style. 

How should we proceed with this? I can foresee several steps, please let me know if you have other ideas:
- Re-organize the pages you mentioned above
- Create a skeleton of pages we want to create
- Start drafting the content
- Involve @esthermmoturi in all these steps.

**Comment by garethbowen** [comment]
> I believe that some items (as the ones you mentioned in the description of the ticket) are addressed to the CHT core contributors, and some of them (as team conversations, for example) are addressed to Medic team. Nevertheless, they could both live under the same documentation, "GitLab" style.

I totally agree with this. At first I felt slightly awkward about including things like our meeting schedules in the CHT docs site, but if it's phrased right then I think it'll be informative to non-Medic readers too.

> How should we proceed with this?

I like your list for first steps, presumably done in that order. I'm happy to help or hand off to you, whichever you prefer.

**Comment by andrablaj** [comment]
You know better the existing documentation and you already have a plan on how to reshuffle pages in a new structure, so please go ahead with the initials changes you suggested when opening the ticket. I can contribute further from there with adding new pages (as needed) and having discussions with the developers on guidelines.
Thanks!

**Comment by garethbowen** [comment]
The first cut (re-arrange everything) is merged.

@andrablaj I think the best way forward would be to split the rest of the work into individual issues which are more manageable. What do you think?

**Comment by andrablaj** [comment]
I agree @garethbowen, thanks for raising this. 

I believe that some content would fall under "Product/Engineering @ Medic" section. Examples:

- Team: e.g. communication, remote work guidelines
- Continuous Discovery Process
- Quality Assistance & how we do QA @ Medic
- Developer Experience: onboarding (e,g. [app services onboarding page](https://github.com/medic/app-services-team/blob/master/onboarding.md) ).
And many other ideas that I shared [above](https://github.com/medic/cht-docs/issues/895#issuecomment-1340872161). 

Do you have a suggestion with what to start with? I am more than happy to start drafting content.

**Comment by garethbowen** [comment]
@andrablaj Oh those are all great.

1. I'd find a good writeup of CD particularly valuable as we have two FGs onboarding onto the process.
2. Quality Assistance should be next as this is a new concept for most of the team
3. Then onboarding because I don't feel like we have a good story for that right now (after the general Medic onboarding completes)
4. Team - very useful but not as pressing as the other 3 IMO

One thing to keep in mind is this is guidelines for how the CHT community works more broadly than Medic specifically. In some ways that's just a branding change (ie: replace "Medic" with "CHT Community"), but it restricts us to only referring to public resources. We can re-evaluate if this gets too clunky.

**Comment by andrablaj** [comment]
Happy that we are on the same page! 🙌 
I can start putting together the "Onboarding" one, and then the others little by little (and align with the team @esthermmoturi ).
Is there anything else in your mind that we should keep in mind? (before going on holidays)

**Comment by esthermmoturi** [comment]
@andrablaj Nothing on my mind for now. I have been following the conversation closely and will give my input as we go.

**Comment by garethbowen** [comment]
@andrablaj I think after that if you could look through Notion and migrate anything Product specific you find there to supercharge our openness!

**Comment by andrablaj** [comment]
Closing the ticket @garethbowen as we should tackle the new Contributor Handbook pages by individual issues. Happy to have this live. 🥳

**Comment by andrablaj** [comment]
Closing the ticket @garethbowen as we should tackle the new Contributor Handbook pages by individual issues. Happy to have this live. 🥳
