### ISSUE TITLE
Improve 'Self Hosting in CHT 3.x'

### ISSUE THREAD

**Issue by kawerewagaba** [medic/cht-docs#906]
Page: /apps/guides/hosting/3.x/self-hosting/
Version: 2022-10-31 14:34:56 -0700 -0700
---

Add `container_name` for medic-os and haproxy. Also add `name` for volume and network.

**Comment by esthermmoturi** [comment]
Done -  https://docs.communityhealthtoolkit.org/hosting/3.x/self-hosting/
