### ISSUE TITLE
Include more context and info in 'Releasing'

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#921]
Page: /contribute/code/releasing/
Version: 2022-12-13 09:17:47  1300  1300
---

The release page should include more context about releases, like when and why a release is made, and who should be requesting one.

> [Create an issue](https://github.com/medic/cht-core/issues/new/choose) for either a Major/Minor or Patch release issue template and assign it to the release manager to follow the process.

How would a release manager know the process? Can we include or link to the process here? Also, assign someone to the new issue to be release manager is only possible for those with the right permissions, so we should make it clear on who should be doing this.

**Comment by abbyad** [comment]
@andrablaj was this already being addressed with https://github.com/medic/cht-docs/pull/918? If so, apologies, and happy to close in favour of the larger scoped https://github.com/medic/cht-docs/issues/895.

**Comment by andrablaj** [comment]
@abbyad no, this enhancement is not addressed in #918, so we can keep this issue separate for now.
